### ISSUE TITLE
Create a slack - discourse oauth integration

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#10]
https://github.com/4xposed/oauth-slack-discourse

**Comment by fvcproductions** [comment]
If we're using Typeform or even Google Forms, we can also make it easier on us to just send a DM in Slack everytime someone signs up.

This would be easier to setup so less technical burden. 😄 

For Typeform integration, see https://zapier.com/apps/slack/integrations/typeform and https://zapier.com/apps/slack/integrations/typeform/883/notify-your-team-on-slack-when-your-typeform-form-has-a-new-entry

**Comment by fvcproductions** [comment]
@dvidsilva could you explain what this integration will do? 🤔

**Comment by fvcproductions** [comment]
Still not sure what this entails - more details would be great! :smile:

**Comment by fvntr** [comment]
@techqueria/website I think this should be closed until enough specs are gathered

**Comment by fvcproductions** [comment]
@dvidsilva Will close for now as @fvntr mentioned - feel free to reopen with more deets tho. 👍
