### ISSUE TITLE
change wording on div near footer on home page 

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#100]
"Whether you just got here last week or your family has been in the country for decades, we have a lot to share and be proud of." 

cause some latinxs have been here longer than decades

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by YourMobileGeek** [comment]
Just doubled checked I believe this was already updated in the footer, right?

**Comment by fvcproductions** [comment]
@fvntr This was already done so I'm going to close the issue! 👍 

Thanks for checking @YourMobileGeek!

**Comment by fvntr** [comment]
Did you want to take this @YourMobileGeek

**Comment by YourMobileGeek** [comment]
@fvntr Yes I can go ahead and take this issue on! Is there a preferred wording/context for the footer that I can reference?, want to be sure I don't say anything that's improper.

**Comment by YourMobileGeek** [comment]
Went ahead a created a pull request for this: #165

**Comment by fvntr** [comment]
Thanks @YourMobileGeek !
