### ISSUE TITLE
Verify domain for GitHub

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#105]
This way, we can get a verified check for our GitHub org. ✅ 

https://github.com/organizations/techqueria/settings/domains

I would do this but it looks like we're not using Netlify DNS for domain configuration - would this be something you're open to transitioning to @dvidsilva? Otherwise, could you let me know which domain provider we're using so I can note that in docs somewhere later? 😄 

I use it for my personal projects and I haven't found any issues with it. 

https://www.netlify.com/docs/dns/

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by dvidsilva** [comment]
there's a lot of dns settings like for G Suite and the sort, so I just added it on cloudflare :D is verified now

**Comment by fvcproductions** [comment]
Gotcha - no worries

**Comment by fvntr** [comment]
Can you put those creds in the password manager so @fvcproductions can have access
