### ISSUE TITLE
Change the Copyright 2016-2018

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#114]
change copyright 2016 -2018 to something simpler like est. 2016
<img width="269" alt="screen shot 2018-10-26 at 01 24 24" src="https://user-images.githubusercontent.com/1316570/47554335-f5429480-d8bd-11e8-9044-dbdf69c00734.png">

---

> ✅️ By submitting this issue, I have verified the following

* [ ] Checked to see if the issue has already been discussed before 🤔️
* [ ] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by YourMobileGeek** [comment]
@fvntr I can go ahead and take on this issue.

**Comment by YourMobileGeek** [comment]
Went ahead and submitted a PR for this for the time being. #143
