### ISSUE TITLE
Update newsletter layout to reflect Techqueria theme

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#12]
For the MailChimp newsletter (if that's still an active thing), we should update the layout to coincide with the techqueria theme more. 

See https://eepurl.com/c5xNWX

Example of Typeform with Techqueria theme (this should be migrated to Techqueria Typeform account!): https://fvcproductions.typeform.com/to/FpJlJp

**Comment by fvcproductions** [comment]
I can help with this if I get access to MailChimp newsletter (assuming it's still a thing Techqueria wants to invest time/effort in maintaining). Otherwise, we should just remove newsletter reference.

**Comment by fvntr** [comment]
@dvidsilva tried getting access to this but the password isnt working

**Comment by fvntr** [comment]
I got ya @fvcproductions
