### ISSUE TITLE
Header nav should be dropdown navigation bar to help navigate the site

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#154]
## Is your feature request related to a problem?
Its hard to some parts of the site like resources, it would be easier if the header nav had a dropdown for each section that related to it

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Want to access resources/press without having to scroll down page

## Describe the solution you'd like
Dropdown navigation bar

> A clear and concise description of what you want to happen.
Dropdown navigation bar for header

## Describe alternatives you've considered
Links for each part of the site but that wouldnt work too well for a header

> A clear and concise description of any alternative solutions or features you've considered.
Dropdown navigation bar for header

## Additional context

> Add any other context or screenshots about the feature request here.

Example from CreditKarma
<img width="388" alt="screen shot 2018-10-27 at 22 35 52" src="https://user-images.githubusercontent.com/1316570/47612500-db798c80-da38-11e8-98cb-d3d3ccf3a53b.png">

**Comment by TiffanieJ** [comment]
/request Hi - can I tackle this one

**Comment by fvntr** [comment]
Yes its yours @TiffanieJ

**Comment by cclaro** [comment]
@fvntr pull-request added, thanks.

**Comment by fvntr** [comment]
I will finish adding the last details on this @cclaro 
Thank you for your contribution
