### ISSUE TITLE
Sponsor cards should link to more event information instead of being external links

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#156]
## Is your feature request related to a problem?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Sponsor links are directing to the companies site. We should be giving more details about the events we held at those places and the nature of our relationship.  

## Describe the solution you'd like

> A clear and concise description of what you want to happen.

Sponsor card should reveal more info about events we've held at those places

## Describe alternatives you've considered

> A clear and concise description of any alternative solutions or features you've considered.

N/A

## Additional context

> Add any other context or screenshots about the feature request here.

N/A

**Comment by darrylbalderas** [comment]
Maybe to upcoming eventbrite events hosted by that sponsor 😜

**Comment by ejbryant28** [comment]
I think this would be a big improvement to the website. I'd be happy to do it if someone describes what event information I should include/where to get it.

**Comment by ejbryant28** [comment]
Should it be the same as the 'more info' button on the events page?

**Comment by ejbryant28** [comment]
I can work on a general template and fill it with vague information for each company (like when they've hosted events) then over time you can add more detail. It might take me a little while to do though. I have limited experience with this framework

**Comment by fvntr** [comment]
any update on this?
