### ISSUE TITLE
Add mixpanel to sponsors

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#157]
## Is your feature request related to a problem?
Need to add Mixpanel since they hosted 10/17 event in sf

## Describe the solution you'd like
Mixpanel logo on event sponsor section

## Describe alternatives you've considered
N/A

## Additional context
![51979f85d525c50d99b44fd377fa4a3c9a258f01](https://user-images.githubusercontent.com/1316570/47623719-f3e9b580-dad1-11e8-9b2e-7c0aa595c211.png)

**Comment by ejbryant28** [comment]
Can I take this issue?

**Comment by fvntr** [comment]
Yes its yours @ejbryant28

**Comment by fvcproductions** [comment]
This was done!
