### ISSUE TITLE
Redesigning community list

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#158]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
Use logos instead a wall of text

## Describe alternatives you've considered
None

## Additional context
We could have it divide like this on the horizontal or vertical with national platform logos taking their own space: 

SF
[logo] [logo] [logo]
LA
[logo] [logo] [logo]
NY
[logo] [logo] [logo]

<img width="203" alt="screen shot 2018-10-29 at 7 10 23 am" src="https://user-images.githubusercontent.com/1316570/47655295-f12aa700-db49-11e8-834d-3c771a90817e.png">
<img width="404" alt="screen shot 2018-10-29 at 7 10 40 am" src="https://user-images.githubusercontent.com/1316570/47655297-f2f46a80-db49-11e8-92f2-22126fd0ff76.png">

**Comment by fvntr** [comment]
@WilliamMena any further work on this needed?

**Comment by WilliamMena** [comment]
I think after our discussions we landed on keeping it like this. So we can
close the issue.
