### ISSUE TITLE
Add a contributors page 

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#16]
Create a page where we show faces and names of contributors with links to their contact, to highlight the contributions of folks, it can be its own page or under the contributing page.

**Comment by fvcproductions** [comment]
Is this specifically for contributors to the website?

At https://beta.techqueria.org/contributors - we could show cards of their faces and name with an external link to their GitHub/LinkedIn - similar to how https://beta.techqueria.org/testimonials works.

**Comment by dvidsilva** [comment]
Yes, different to the volunteers page or teammates that's in about

**Comment by santos22** [comment]
👋 
What if we did something like this project? https://github.com/paypal/glamorous#contributors
I've seen it done elsewhere and IMO it puts the recognition front and center.

**Comment by fvcproductions** [comment]
@santos22 We could potentially do both - have a dedicated section in README for contributors and also have a web page for it on Techqueria.

Having both would require more maintainability but it's @dvidsilva's call.

**Comment by dvidsilva** [comment]
We can leave the list only on readme for now, and if it increases too much we can reconsider to avoid the duplication.
