### ISSUE TITLE
Some logos still cutoff on desktop 

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#168]
## Describe the bug

Image for certain cards are cutoff. 

## To Reproduce

> Steps to reproduce the behavior

Go to https://techqueria.org/resources/open-source/ and check operation code
Go to https://techqueria.org/sponsors/ and check yammer informedk12 and twilio

## Expected behavior

Logo with no cutoff

### Desktop

 - OS:  MacOS on Firefox

**Comment by fvntr** [comment]
did you do npm install? pull from upstream and install since there were some module changes recently.

**Comment by fvntr** [comment]
mixpanel is done
informedk12 and operation code are still pending

**Comment by YourMobileGeek** [comment]
<img width="1014" alt="screen shot 2018-11-08 at 12 04 40 pm" src="https://user-images.githubusercontent.com/8063614/48215198-b72e8180-e34f-11e8-9702-61bd6418802f.png">

Yup, that's the first thing I thought about doing and it's recognizing the updates made to the project. I even referenced this for syncing a fork ( [https://help.github.com/articles/syncing-a-fork/](https://help.github.com/articles/syncing-a-fork/) ) 
-
@fvntr

**Comment by fvntr** [comment]
ok have your tried rm -rf node_modules
then doing an npm install

**Comment by YourMobileGeek** [comment]
Yup that actually worked for me, so odd. Thanks for your patience too!

**Comment by YourMobileGeek** [comment]
Fixed informedk12 and operation code logo and submitted a PR request: #184
