### ISSUE TITLE
Non-working download link in Health Care section

### ISSUE THREAD

**Issue by Ismael-Duran** [techqueria/website#171]
Non-working link **Download PDF** for "California Health Care Resource Guide ...." under Techqueria -> Resources -> Health Care
---

> ✅️ By submitting this issue, I have verified the following

- [ x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [ x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by fvntr** [comment]
Thanks Ismael for bringing this to our attention. Just made a pr

**Comment by fvntr** [comment]
Resolved
