### ISSUE TITLE
Create form to collect feedback/testimonials

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#172]
## Is your feature request related to a problem?
Currently there is no way to collect testimonials/feedback besides an email

## Describe the solution you'd like
A form to collect testimonials/feedback

## Describe alternatives you've considered
This can be a google form, collect through newsletter

**Comment by WilliamMena** [comment]
I haven't used google forms all that much but I saw that there should be a way to embed it into the website. So maybe that can be an option. Or just linking to the form on the website as well to make it easy lol.

**Comment by fvcproductions** [comment]
@fvntr @WilliamMena This would be best as a Netlify form because of the integrations - related issues are #153 #95

**Comment by fvcproductions** [comment]
Let's make sure to get the form fields/design set up too so it's easier for assigned contributor to work on this once we setup our first Netlify form 😄

**Comment by fvntr** [comment]
will work on this and #54 in parralel
