### ISSUE TITLE
Adding mental health resources

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#186]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

Adding mental health resources to health resources
https://therapyforlatinx.com/
https://www.counselingandtraumatherapy.com/bienvenidos

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by YourMobileGeek** [comment]
@fvntr I could take this on, should be a quick update to apply.

**Comment by YourMobileGeek** [comment]
Just created pull request for this issue: #211

**Comment by fvntr** [comment]
Resolved with https://github.com/techqueria/website/pull/211
thanks @YourMobileGeek !
