### ISSUE TITLE
Add techqueria open-source initiatives under open-source in resources

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#189]
## Is your feature request related to a problem?
No

## Describe the solution you'd like

Include the following projects under open-source in resources: 

* https://github.com/techqueria/website
* https://github.com/techqueria/data-and-algorithms
* https://github.com/techqueria/frackmap

## Describe alternatives you've considered

N/A
> A clear and concise description of any alternative solutions or features you've considered.

## Additional context

> Add any other context or screenshots about the feature request here.

**Comment by YourMobileGeek** [comment]
@fvntr I can look into taking this issue on, if no one was was working on this. 👀

**Comment by fvcproductions** [comment]
@fvntr Just a heads up, the `in progress` label should be added to issues to indicate someone is going to work on it. Thanks! 😄 

https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md#issue-tracker

**Comment by YourMobileGeek** [comment]
@fvntr @fvcproductions Is there an alternative link for the third website url listed? It's outsourcing to a 404 error page.

**Comment by fvcproductions** [comment]
@YourMobileGeek It was probably archived - I would ignore for now!

**Comment by YourMobileGeek** [comment]
@fvcproductions okay sounds good, thanks! Just went ahead and created a pull request for the current active links. #213

**Comment by fvntr** [comment]
Resolved w https://github.com/techqueria/website/pull/213
