### ISSUE TITLE
Migrate remaining blog posts from medium to site

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#193]
## Is your feature request related to a problem?

Migrate remaining blog posts from medium to site

## Describe the solution you'd like

Medium posts should be on the site now

## Describe alternatives you've considered

n/a

## Additional context

https://blog.techqueria.org/

**Comment by fvcproductions** [comment]
@jose8a we've just been copying the images/text manually 😬

**Comment by jose8a** [comment]
@fvcproductions I just accepted to join the org.  Will start working on this issue tomorrow.  Thx!

**Comment by fvcproductions** [comment]
Will work on this since I have some downtime 👍
