### ISSUE TITLE
Decide GitHub repo structure

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#20]
How should we manage the development of the website for the long run?

Should we use a tool like [ZenHub](https://www.zenhub.com/) or [Waffle.io](https://waffle.io/) or just organize things using GitHub Projects?

How do we decide which issues to prioritize and do we have plans to have timelines for releases or new versions of the website?

Just would like to get thoughts and idea on how continuous integration/development will work through GitHub. 😄 

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
Just to add on to this, this is how repo looks with ZenHub extension:

<img width="1918" alt="screenshot 2018-07-12 20 06 27" src="https://user-images.githubusercontent.com/4284691/42670356-1d6e1472-860f-11e8-8d26-bad0c73ae9a6.png">

**Comment by fvcproductions** [comment]
Also related to this, @dvidsilva would it be possible to remove *Wiki* tab in repo settings since we probably won't be using that feature?

**Comment by dvidsilva** [comment]
I really like waffle, I can activate a board there if we want!

**Comment by dvidsilva** [comment]
I added a board here, will send a PR with a link to this in the README https://waffle.io/techqueria/website

**Comment by fvcproductions** [comment]
Since we've decided to use Waffle.io, I will go ahead and close this issue.
