### ISSUE TITLE
Meetup Group is Actually National

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#210]
## Describe the bug

Meetup group in Bay Area Chapter page is actually not a local group anymore. It is being used by Chicago Chapter. 

## To Reproduce

> Steps to reproduce the behavior

techqueria.com/communities/bay-area/

## Expected behavior

remove meetup group 

## Environment
All

### Desktop

All

### Mobile

All

## Additional context

n/a

**Comment by YourMobileGeek** [comment]
I can take on this issue, seems like a quick fix in regards to removing the meetup group.

**Comment by fvntr** [comment]
great I will assign!
can you move it from bay area to https://techqueria.org/communities/ ?

**Comment by YourMobileGeek** [comment]
Just submitted a pull request: #226
