### ISSUE TITLE
Apply for 1Password team password manager (open source)

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#214]
## Is your feature request related to a problem?

Yes, we need a more efficient way to share passwords for Techqueria org stuff

## Describe the solution you'd like

Apply here: https://github.com/1Password/1password-teams-open-source

## Describe alternatives you've considered

Looked up a bunch of them and there are not many good options out there for team password managers. ☹️ 

We could upgrade LastPass to Premium but that costs $$

## Additional context

N/A

**Comment by fvntr** [comment]
Is this for site related creds only? @fvcproductions

**Comment by fvcproductions** [comment]
@fvntr Could I get a `@techqueria.org` email to sign up for this? Or maybe you and someone with that email domain could? I think it would help with Techqueria's scalability if we had 1Password to manage all our different accounts.

**Comment by fvcproductions** [comment]
Done 👍 

https://github.com/1Password/1password-teams-open-source/pull/98

**Comment by fvcproductions** [comment]
@fvntr exciting news - our application was accepted! 🎉

Please read this (https://github.com/1Password/1password-teams-open-source/pull/98#issuecomment-461903785), invite the core team to the new 1Password account, add the logo as the main image and let folks know in the appropriate channels. I would help with this but I'm on PTO. 🌴

**Comment by fvcproductions** [comment]
Let's close this - we do plan on migrating from LastPass to 1Password.

cc @fvntr
