### ISSUE TITLE
Improve the contributing guide

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#23]
The contributing guide  is not very clear yet on what the platform are we using, so is not easy to know how to add new content.

It would be good to have more information about the content, layouts, partials, commands, and pre-processors being used.

**Comment by fvcproductions** [comment]
I agree this needs some work so I will be sure to cook something up soon that elaborates on Hugo and how to use it with this website.

**Comment by fvcproductions** [comment]
I tried to elaborate on this within README/Contributing but more work needs to be done in comments within the source code. I will focus on this with the minor redesign.
