### ISSUE TITLE
i18n (Spanish translations)

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#236]
Right now, part of the website is translated in Spanish.

For example: https://techqueria.org/es/contact/

We would like to get the entire website translated.

How to contribute to translations are explained here: https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md#translations

If you are bilingual and would like to contribute, let us know which page you would like to translate so we can create a separate issue to track the progress. 

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by enriquenov** [comment]
Hi @fvcproductions, I'm going to help translating some of the content. 👍

**Comment by omarnyte** [comment]
Hey, @fvcproductions! I'd love to get started contributing with some translations. I can work on all of the "Support Us" pages.

**Comment by fvcproductions** [comment]
@omarnyte Brilliant - you can open a PR when you're ready and feel free to ask me any questions you have on how to submit translations

**Comment by omarnyte** [comment]
@fvcproductions

**Comment by omarnyte** [comment]
@fvcproductions, I'm having some trouble hitting `/es/donate-space/`, `/es/volunteer/`, and `/es/supporters/.` In production, those routes display a 404. Locally, they show a blank page with a `Cannot GET` error.  `/es/support-us/` works as expected. I've tried adding the URLs to the sitemap on `config.toml`, but I'm still not hitting any of those routes. How can I configure those URLs?

**Comment by cyberfernandez** [comment]
Hola, I would love to contribute to this project. Any other words of advise to get started ?

Thanks,

**Comment by fvcproductions** [comment]
@cyberfernandez Thanks for reaching out - contributing guidelines are here so I would use that to get started https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md#translations and you're welcome to ask me any questions!
