### ISSUE TITLE
Fixed the Insecure mixed content detected warning

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#241]
## Describe the bug

when deploying to netlify we're getting an error that mixed content is being served

## Expected behavior

All the images are served with https

## Environment

```
Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection. Learn more about mixed content.

In resources/podcasts/conexiones/index.html:

Insecure img urls:
http://conexiones.io/wp-content/uploads/2018/03/facebook-cover2-1.jpg
In resources/podcasts/valle-de-los-tercos/index.html:

Insecure img urls:
http://www.elvalledelostercos.com/uploads/9/1/9/9/91997288/editor/1477090467.png?1522173206
In sponsors/hackbright-academy/index.html:

Insecure img urls:
http://innov8tiv.com/wp-content/uploads/2018/06/hackbright-academy-1-750x400.jpg
In sponsors/udacity/index.html:

Insecure img urls:
http://www.judycheadesign.com/wp-content/uploads/2015/05/Logo_Gradient_Web.jpg
In sponsors/yammer/index.html:

Insecure img urls:
http://allvectorlogo.com/img/2017/05/yammer-logo.png
```

**Comment by dvidsilva** [comment]
@fvcproductions  maybe related to this or not, but like in people, most images are not being served https://techqueria.org/people/

**Comment by fvcproductions** [comment]
@dvidsilva Oops that's another issue entirely. The images are grabbed from LinkedIn and they've probably been called too many times from that page and are now no longer showing. Solution would be to just download the profile images from LinkedIn and serve them locally instead.

**Comment by dvidsilva** [comment]
Oh okay good point. I thought chrome finally decided to not serve mixed content.  Easy one then. I can try this weekend
