### ISSUE TITLE
Upload people images locally

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#244]
Pulled in from the discussion in #241 

## Describe the bug

On https://techqueria.org/people/, a bunch of images are not showing because they are URLs grabbed from LinkedIn and are probably no longer valid.

## Solution

Get the images of the organizers and host them locally in the `src/images` folder instead OR host them on an image sharing site like Imgur.

<img width="1398" alt="screen shot 2019-01-17 at 5 53 03 pm" src="https://user-images.githubusercontent.com/4284691/51360504-ca14af00-1a80-11e9-86f0-bb3679868fc1.png">

**Comment by fvcproductions** [comment]
@jose8a are you already working on this?

**Comment by fvcproductions** [comment]
If not, I can go ahead and take this

**Comment by jose8a** [comment]
@fvcproductions I haven't started on this yet. I plan on working on #193 first, beginning tomorrow.

**Comment by fvcproductions** [comment]
sounds good - I'll assign to myself

**Comment by fvcproductions** [comment]
Fixed in #256
