### ISSUE TITLE
Increase GitHub Stars to over 100 ⭐️

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#266]
https://github.com/opencollective/opencollective/issues/1755#issuecomment-466119947

"If you would like to be fiscal sponsored by the Open Source Collective then you'll need at least a repo of 100 stars. If you have a bank account you can use, then you just need to go to your collective /edit and select fiscal host and create your own host organization. You just need to have a stripe account."

Let's ask the Techqueria community to star this repo so we can get over 100 stars!

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by fvntr** [comment]
we are at 104 stars 🎉as of 4/5/2019
