### ISSUE TITLE
Update Code of Conduct

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#279]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
Add the following to CoC: 
"For all official Techquería events, in instances where alcohol is present, the following is required:
* All attendees must have IDs checked to confirm they are 21+
* Alcohol consumption must be limited. Local chapters maintain autonomy for how to implement alcohol control measures (drink tickets, wristbands, etc). Additionally, it is at the local chapter’s discretion how to handle alcohol at casual events."

**Comment by quahada** [comment]
putting some issues into writing & adding some more suggestions from folks who run other communities:
"spamming the group and excessive self promotion are not allowed"
"members must follow the social norms of the community"
"finding loopholes in the code of conduct is a violation of the code of conduct"
"if an admin or organizer has to talk to you about the code of conduct, you've already violated it"

**Comment by fvcproductions** [comment]
@quahada the second to last one seems a bit harsh 😬 

also where are u taking these from out of curiosity?

**Comment by quahada** [comment]
good point about it being too harsh. I'm open to something more gentle.
1st couple were reactions to some admin action we've had to take. The last 3 were from talking to another community organizer (outside of tech, can't remember who exactly) about ways to improve the COC & community in general.

**Comment by fvcproductions** [comment]
I think we should just omit "If an admin or organizer has to talk to you about the code of conduct, you've already violated it" since "Any action that results in complaints from our community is a violation of the code of conduct" kinda covers it?
