### ISSUE TITLE
Slack Invite CTA

### ISSUE THREAD

**Issue by quahada** [techqueria/website#281]
Is it possible to make the Slack invite call-to-action more prominent & visible, especially on mobile?

on this page: https://techqueria.org/communities/slack/
the link to the google form is below-the-fold & is a link instead of a CTA button.

Also, in the "Join us in Slack! 💬" section of the homepage, make the button blue background with white text.

The context behind this request is going to a meetup & someone asks to join the slack. I ask them to go to techqueria.org & see they have a hard time finding where to join, which can result in them missing out on converting to a community member. For those that don't have one of us holding their hand through the process, I imagine this could be a big problem

**Comment by fvcproductions** [comment]
@quahada I agree this could definitely be more prominent 👍

**Comment by KGmajor** [comment]
I'd love to help here. I'm a new software engineer, but I'm pretty sure I can handle some buttons!

**Comment by fvntr** [comment]
Sent an invite over to contributor team

**Comment by fvcproductions** [comment]
https://github.com/techqueria/website/pull/282 is opened to address this

**Comment by fvcproductions** [comment]
This was completed!
