### ISSUE TITLE
Add New Resource: NHAC

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#283]
## New Resource Request

We received an email to add "Nursing Home Abuse Center (NHAC)" to our health resources page.

https://www.nursinghomeabusecenter.com/

https://techqueria.org/resources/health/

## Email

I came across Techqueria while searching for organizations with the common goal of supporting the LGBT community. 

Our main focus is spreading awareness to LGBT seniors being mistreated and often abused in nursing homes and other support facilities.

There are approximately 3 million LGBT seniors over the age of 65, and this number is projected to double by 2030. 

*And sadly, as more LGBT community members come out, there are more abuse cases being reported especially within the senior community.* 

Of particular concern is housing discrimination, both in terms of access to housing and the treatment they receive once there. 

Access to safe and equal-opportunity housing is a fundamental right, but in practice, LGBT members face larger obstacles in finding comfortable living situations.

As the Director of Advocacy at the Nursing Home Abuse Center (NHAC) my goal is to ensure that our message reaches the people who need to see it the most. 

I’m asking you for help with this. 

By adding us to your resource page here - https://techqueria.org/resources/health/ it would go a long way towards achieving our goal of spreading awareness about these issues. 

I truly appreciate your support.

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by enriquenov** [comment]
Hi @fvcproductions! Was this issue solved in the unmerged PR you submitted 3 days ago? If not, I'd like to get it done. 👍

**Comment by fvcproductions** [comment]
@enriquenov Yeah I'm still working on it, PR should be merged in soon once I fix the formatting issues 😄
