### ISSUE TITLE
Add New Resource: ShopLatinx.com

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#284]
Add shoplatinx.com to resources under business/entrepreneurship

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by enriquenov** [comment]
Hi @fvcproductions, I'm tackling this issue right now. Please consider/label it as "in progress". 

Thanks!
