### ISSUE TITLE
Add CodeTriage badge to README

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#286]
[![Open Source Helpers](https://www.codetriage.com/techqueria/website/badges/users.svg)](https://www.codetriage.com/techqueria/website)

```
[![Open Source Helpers](https://www.codetriage.com/techqueria/website/badges/users.svg)](https://www.codetriage.com/techqueria/website)
```

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by sonali9696** [comment]
I would like to work on this
I will go ahead and add it after the existing badges. Please LMK if you would like to add the badge elsewhere

**Comment by sonali9696** [comment]
I have made the changes and raised a PR for the same. It would be great if you could review it @fvcproductions
