### ISSUE TITLE
Add first-timers-friendly badge to README

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#287]
[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)

```
[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)
```

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by sonali9696** [comment]
I would like to work on this

**Comment by sonali9696** [comment]
I have added the badge right after the other badges. Let me know if you had any other location in mind.

**Comment by sonali9696** [comment]
I have fixed the issue and raised the PR: https://github.com/techqueria/website/pull/291/commits.

@fvcproductions it would be great if you could review it :)
