### ISSUE TITLE
Add Techqueria.org to FirstContributions.io site

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#288]
Make a PR to the repo by adding Techqueria.org to this file

https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/listOfProjects.js

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by sonali9696** [comment]
Hi @fvcproductions, I wanted to get the requirement clarified. Do you mean you want an entry of  Techqueria.org to be added to the projectList array?
If yes, could you please LMK what would be the entries of the imageSrc, description and tags for your website?

name: ' Techqueria.org',
imageSrc: ,
githubLink: 'https://github.com/techqueria',
description: ,
tags:

**Comment by fvcproductions** [comment]
@sonali9696 Yes, that's right!

Here are the details

```
imageSrc: https://avatars1.githubusercontent.com/u/17460806?s=200&v=4
description: "We're a community of Latinx professionals in the tech industry."
tags: "latinx", "latinx in tech", "hugo", "netlify", "jamstack"
```

**Comment by sonali9696** [comment]
On observing the UI of https://firstcontributions.github.io/, I have mixed feelings about putting a full stop in the description. According to https://bootsnipp.com/snippets/92xNm, full stop seems like the way to go but some of the cards in https://firstcontributions.github.io/ do not have full stops and they look good to me too. For now, I am proceeding with the full stop but I would like to know your views too @fvcproductions

**Comment by sonali9696** [comment]
The changes have been made and PR has been raised: https://github.com/firstcontributions/firstcontributions.github.io/pull/43. I tried connecting the PR directly to this issue but since it is in a different repo, it was only redirecting to their own issues.

**Comment by fvcproductions** [comment]
@sonali9696 PR looks great with full stop - thanks so much! 👍

**Comment by fvcproductions** [comment]
@sonali9696 Let's close this issue for now since the PR has been opened and it's in their ball game now. I made sure to subscribe to the PR for any future changes. 🌮
