### ISSUE TITLE
Add HeyTaco to Slack Community Guidelines

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#289]
Add how Techqueria uses HeyTaco to give kudos to https://techqueria.org/slack

---

The HeyTaco! bot sparks conversations and builds stronger relationships with its fun and unique kindness currency... tacos! :taco: 
 
Their model fits perfectly with Techqueria's brand so we were so glad when the founders decided to offer us a community discount, making it completely free for all 3000+ of our Slack members when it usually costs $2 bucks per person per month. :shocked facewith explodinghead: 
 
You can learn more about HeyTaco! at  https://www.heytaco.chat  

---

*How @heytaco works* :pushpin:

> You can use @heytaco to give someone a :taco: when you'd like to show praise, appreciation, or to add a little happiness to their day. :hey-taco:

*1. Every person in our Slack Workspace has 5 tacos to give out per day*

:taco: x :five:

*2. To give someone a taco, add a taco emoji after their username*

Like this: `@username your positive attitude was a real help today! :taco:`

*3. You can give tacos to anyone on your team as long as the bot has invited to the channel*

You can invite the bot to channels using `/invite @heytaco`

*4. There is a leaderboard to see who is getting the most tacos*

Anyone in our Slack Workspace can sign in and see the leaderboard using https://www.heytaco.chat/leaderboard

*5. Need help?*

If you need help, you can just DM @heytaco the word `help` and it will assist you (edited)

**Comment by enriquenov** [comment]
Hi @fvcproductions, I'd like to work on this issue as well. 🤓

Q: Is it okay to add the HeyTaco! how-to instructions under **Best Practices** in the Slack Guidelines?

**Comment by fvcproductions** [comment]
@enriquenov Actually let's put this under "Customization" and make it the first item. 👍 

I would also include a screenshot of how HeyTaco works from the HeyTaco website for better clarity!

**Comment by enriquenov** [comment]
@fvcproductions sounds good, I'm on it!
