### ISSUE TITLE
Highlight Patreon Supporters on Website

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#290]
Highlight our Patreon supporters on a new "Supporters" page https://techqueria.org/supporters

Name: "Supporters 💛 "
Description: "We want to recognize our Patreon supporters for their financial support."
Image: See attachment, make sure to make download to repo and make it a locally referenced image

![Patreon Supporters](https://user-images.githubusercontent.com/4284691/54970798-e29dbb80-4f40-11e9-86d8-62fd5910ab16.png)

Use their Twitter, not Patreon accounts for linking and make sure to include a high-res image

Each supporter should have their own card with an image, name and brief description

These are our current 3 supporters on Patreon:

- Phillip Ventura: https://www.patreon.com/user/creators?u=14572309
- Javier Lopez: https://www.patreon.com/cupto/creators
- Xande Macedo: https://www.patreon.com/xande/creators

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by enriquenov** [comment]
Hi @fvcproductions, I'm working on creating the "Supporters" page tonight.

**Comment by enriquenov** [comment]
Hey @fvcproductions, I put Phillip's LinkedIn for now, because I can't find his twitter account anywhere.
