### ISSUE TITLE
Add non-profit resources

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#294]
## Request

Look up all the resources provided below and add them to a new section of the website:

https://techqueria.org/resources/non-profits

## Resources

- Google for non profits
- Slack for non profits
- Facebook for non profits
- https://ycombinator.com/nonprofits
- https://microsoft.com/en-us/nonprofits
- https://gatesfoundation.org/How-We-Work/General-Information/Grant-Opportunities
- https://chanzuckerberg.com
- https://www.techsoup.org
- http://diversity.techstars.com/foundation
- http://praxislabs.org/nonprofit
- http://ffwd.org/accelerator
- http://tt-exchange.org

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by avaldivi** [comment]
hi  👋 @fvcproductions I'd like to work on this. Should I copy the same format that the community page has or does this have a design in place?

**Comment by fvcproductions** [comment]
Thanks @avaldivi! 👍 

So the format would look just like https://techqueria.org/resources/bay-area/

What you'll need to do is to create a new folder for the new nonprofit page under the resources folder and then set up the main `index.md` file along with all the resources mentioned in this issue. 

This issue is a bit bigger as it will require you to look up the images in order to create the card with the link. 

Let me know if you have any questions though, I'm here to help!

**Comment by avaldivi** [comment]
@fvcproductions Thanks for the extra info. No problem with me. I will get started on it this weekend.

**Comment by fvcproductions** [comment]
@avaldivi Let me know if you can still work on this, I sent u an invite to the GitHub org as well

**Comment by sonali9696** [comment]
Please LMK if any help is needed with this issue, I would be happy to work on this.

**Comment by fvcproductions** [comment]
@sonali9696 I'll assign this to you for now since I haven't heard back from @avaldivi 👍 

Quick edit:

I've learned recently that in terms of naming conventions, we want this to be:

https://techqueria.org/resources/nonprofits instead of https://techqueria.org/resources/non-profits

**Comment by sonali9696** [comment]
Sure, thanks! :) I will start this weekend

**Comment by sonali9696** [comment]
Hey @fvcproductions, I needed a small clarification. You mentioned that a new folder needs to be created under resources folder but I guess you have optimized the directory structure and now the nonprofit folder should be under "dist" folder just like entrepreneurship. Please correct me if I am wrong.

**Comment by sonali9696** [comment]
Hi @fvcproductions, the link you had given before leads to the entrepreneurship ( https://techqueria.org/resources/bay-area/) but after you optimized the directory structure, I have a feeling that you want the structure to be similar to https://techqueria.org/communities/chapters/bay-area/. Is that correct?

**Comment by sonali9696** [comment]
Hey @fvcproductions, I needed a little clarification. You needed the format to be the same as https://techqueria.org/resources/bay-area/ but this leads to entrepreneurship page. I guess you mean that you need it same as https://techqueria.org/communities/chapters/bay-area/. This redirection has probably changed recently while optimizing the directory structure. I have raised an issue of this as well. (https://github.com/techqueria/website/issues/320). Please let me know if I am mistaken.

**Comment by fvcproductions** [comment]
@sonali9696 Apologies for the confusion - https://techqueria.org/resources/bay-area/ used to be a resources category for entrepreneurs in the Bay Area but it was merged in with a more generic page for entrepreneurship. https://techqueria.org/resources/entrepreneurship/

The comment was made before these changes were made but what you are describing is intentional and not a bug. Thank you for raising!

**Comment by avaldivi** [comment]
@fvcproductions @sonali9696 whoops! I was only halfway done then got swamping with a work project. @sonali9696 do you got this?

**Comment by sonali9696** [comment]
Thanks for the clarification @fvcproductions! @avaldivi Yeah, I got this! :)

**Comment by sonali9696** [comment]
Just like entrepreneurship has the description as: "Resources related to businesses by Latinx Entrepreneurs.". What would you like for the nonprofits page @fvcproductions. For now, I have written "Resources related to non-profits"

**Comment by fvcproductions** [comment]
@sonali9696 

1. The description you have works great! 💯 

2. That one can be used for now 👍 

@avaldivi no worries - completely understandable 💛

**Comment by sonali9696** [comment]
The task is complete and PR has been raised @fvcproductions. Link: https://github.com/techqueria/website/pull/323
