### ISSUE TITLE
Add recent news regarding non-profit status & Sentry award

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#297]
- our non-profit announcement as a blog post
- our Sentry award as a blog post
- tax ID number in the footer and on Patreon/Open Collective

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by fvntr** [comment]
is this going to be added to the current sponsor page? under like a heading 'grant'or 'open-source' partner?

**Comment by fvcproductions** [comment]
@fvntr no; as separate blog posts

sentry is done; just need non-profit status one
