### ISSUE TITLE
Add LinkedIn page to navbar & communities

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#300]
## Overview

Add LinkedIn company page to the navbar and Communities section.

## Currently

Current URL is https://techqueria.org/communities/linkedin/ which links to https://www.linkedin.com/groups/13500636

## Request

Instead, we want https://techqueria.org/communities/linkedin/ to link to our company page https://www.linkedin.com/company/techqueria and we want https://techqueria.org/communities/linkedin-group/ to link to https://www.linkedin.com/groups/13500636 with an updated title of "LinkedIn Group"

We also want the LinkedIn page to be added to our navbar

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by shivam15** [comment]
i would like to take this

**Comment by fvcproductions** [comment]
@shivam15 i will send u an invite to join our github org 👍

**Comment by shivam15** [comment]
sure thanks

**Comment by shivam15** [comment]
is it already done? Since in nav bar i can see correct url

**Comment by fvcproductions** [comment]
@shivam15 yes it looks like it was completed already - my mistake! will mark as done 👍
