### ISSUE TITLE
Update supporters with most recent supporters

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#304]
## Is your feature request related to a problem?

We currently have 7 patreon supporters and only 3 are listed 

## Describe the solution you'd like

Add: 
Liliana A Monge https://www.linkedin.com/in/lilianamonge/
Krystal Flores https://www.linkedin.com/in/krystalflores/
Tonatiuh Ramos http://www.tonatiuhramos.com/
Frances Coronel https://www.linkedin.com/in/fvcproductions/

**Comment by fvcproductions** [comment]
@fvntr this is a duplicate of #303
