### ISSUE TITLE
Add other testimonials

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#31]
We can add more testimonials here in the comments to later add them to the website.

**Comment by dvidsilva** [comment]
Techstars Startup Weekend was an unforgettable experience. I was looking to transition from a career in Education to the tech world for a while and when I heard of Startup Weekend I decided to take the leap of faith and get outside of my comfort zone. I had so many thoughts running through my head like, "Will anyone say anything about me being a teacher? Will anyone want me to be part of their group? Honestly, those questions did not matter because everyone was so welcoming and ready to work together. I ended up joining a great team of people with with careers in tech and outside of tech. Techstars start up weekend was such an amazing learning experience because it showed me how a company can be built in 52 hours. This was so rewarding and I would recommend it to anyone looking to learn,network, and be challenged.

- Gina after Startup Weekend Latinx in 2017

**Comment by SneX13** [comment]
I can take this one @dvidsilva 
I need a link to Gina's img and LinkedIn profile, as well as "description" (work title, I assume). 
And if you have more testimonials ready, I can add them as well.

**Comment by fvcproductions** [comment]
@dvidsilva Any update on Gina's info?

**Comment by YourMobileGeek** [comment]
@dvidsilva @SneX13 Was there any update on this by chance? 👀

**Comment by fvntr** [comment]
@SneX13  @YourMobileGeek  
please use the following: https://www.linkedin.com/in/gina-giardinieri/

**Comment by SneX13** [comment]
@fvntr thank you, will do that. Sending PR later today @YourMobileGeek . Do you have more testimonials that should be added?

**Comment by fvntr** [comment]
I am closing this for now. We can gather these via a form on our site. WIll make an issue for that. Thanks @SneX13 for your work on this!
