### ISSUE TITLE
Communities list not showing on Spanish version's footer

### ISSUE THREAD

**Issue by enriquenov** [techqueria/website#311]
## What's going on?

The list of Communities does not show in the footer when switching the page to Spanish.

## How can we reproduce this bug?

1. See footer in Techqueria.org
2. See footer in Techqueria.org/es
3. The communities list does not show for the second one

## What is the expected behavior?

The footer should show the Communities' list in the page's Spanish version.

## Any screenshots?

English 
<img width="681" alt="Screen Shot 2019-04-03 at 12 46 00 AM" src="https://user-images.githubusercontent.com/22536342/55462024-b8847300-55aa-11e9-95d0-6f7ad300c3fb.png">

Spanish
<img width="524" alt="Screen Shot 2019-04-03 at 12 46 32 AM" src="https://user-images.githubusercontent.com/22536342/55462060-cb974300-55aa-11e9-9973-5d1c6d90e66a.png">

## What is your environment?

macOS Mojave, Chrome 73.0.3683.86

**Comment by fvcproductions** [comment]
@enriquenov This is intentional as none of those Community pages have been translated yet - it should show only translated content 👍

**Comment by enriquenov** [comment]
@fvcproductions I see. Good to know!
