### ISSUE TITLE
Add buttons to filter people by location & role

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#314]
## Add buttons to filter by location and role --&gt;

https://github.com/techqueria/website/blob/c3ec4c0672462396aa17195c02b24c9f0ec0b7e9/layouts/section/people.html#L14-L19

---

###### This comment was generated by [todo](https://todo.jasonet.co) based on a `TODO:` comment in c3ec4c0672462396aa17195c02b24c9f0ec0b7e9 in #313. cc @fvcproductions.

_Originally posted by @todo in https://github.com/techqueria/website/pull/313#issuecomment-479659812_

**Comment by fvcproductions** [comment]
Potential libraries you can use to filter people by location and role:

https://www.kunkalabs.com/mixitup/

https://isotope.metafizzy.co/filtering.html

**Comment by fvcproductions** [comment]
Don't want it to be marked as stale but it is a toughie!

**Comment by Sol1323** [comment]
@fvcproductions I would love to work on this issue [#314](https://github.com/techqueria/website/issues/314). :)

**Comment by fvcproductions** [comment]
@Sol1323 I just assigned you - let me know if you have any questions!
