### ISSUE TITLE
Can't access the content in english in some pages

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#318]
## What's going on?

Some pages that exist in spanish became unavailable in english, as in they're getting redirected to the new version

## How can we reproduce this bug?

1. Go to https://techqueria.org/about/photos

## What is the expected behavior?

It should display content/photos/index

**Comment by fvcproductions** [comment]
Thanks for raising the issue @dvidsilva - I'll look into it!

**Comment by fvcproductions** [comment]
It's because the same URLs were being used - will fix now.

**Comment by dvidsilva** [comment]
Great work! thanks @fvcproductions
