### ISSUE TITLE
https://techqueria.org/resources/bay-area/ leads to entrepreneurship page not bay area chapter

### ISSUE THREAD

**Issue by sonali9696** [techqueria/website#320]
## What's going on?

On navigating to https://techqueria.org/resources/bay-area/, the entrepreneurship is loaded instead of the bay area chapter.

## How can we reproduce this bug?

1. Go https://techqueria.org/resources/bay-area/
2. You would see the entrepreneurship page.

## What is the expected behavior?

It should probably redirect to https://techqueria.org/communities/chapters/bay-area/ instead.

## What is your environment?

Windows 10, Chrome version 73.0.3683.103 (Official Build) (64-bit)

## Any additional context?

This probably began after optimizing the directory structure

**Comment by fvcproductions** [comment]
@sonali9696 This is not a bug - see https://github.com/techqueria/website/issues/294#issuecomment-480623314

Thank you for raising!
