### ISSUE TITLE
Add nonprofit link to navbar

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#330]
## Feature Request

https://techqueria.org/resources/nonprofits should be added to dropdown navbar

## Any additional context?

See #323 for more context

**Comment by teisenhower** [comment]
I'd love to assist on this and a few other issues you have posted, if no first timers claim them.

**Thanks!**

**Comment by fvcproductions** [comment]
@teisenhower Definitely, feel free to tackle it and let me know if you have any questions!

**Comment by teisenhower** [comment]
Great! Thank you! I will make a PR soon.

**Comment by fvcproductions** [comment]
@teisenhower Turns out it was added in a previous PR and I just didn't notice it - good to go now!
