### ISSUE TITLE
Remove emoji from navbar dropdowns

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#331]
## Request

Let's remove emoji from dropdown navbar items

## Why did you make this request?

We want to come across as more professional 😂😬

## Any additional context?

N/A

**Comment by finncodes** [comment]
Hello,

Could I work on this issue?

**Comment by fvcproductions** [comment]
@teisenhower feel free to tackle this one - it's pretty easy since you're just getting rid of emoji in the navbar within `config.toml`

**Comment by teisenhower** [comment]
@fvcproductions Thanks! Will do!
