### ISSUE TITLE
Add Slofile to Slack page

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#335]
## Link where content currently exists

https://techqueria.org/communities/slack

## Updates you'd like to make

Add https://slofile.com/slack/latinos at the end of the sentence "As you are waiting for your Slack invite" with "You can also get a taste of our Slack workspace by checking out [Slofile profile](https://slofile.com/slack/latinos)."

## Any additional context?

N/A

**Comment by KonradGladala** [comment]
Hello, I would like to help you with this.

**Comment by fvcproductions** [comment]
@KonradGladala Sure go ahead!
