### ISSUE TITLE
Create new resource page for "similar organizations"

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#336]
## Request

Let's add a page under resources located at https://techqueria.org/resources/similar-orgs with the title "Similar Organizations 👀"

## Why did you make this request?

Let's showcase other friendly organizations dedicated to supporting Latinx in Tech.

## Any additional context?

Yes, here are a few organizations we would like to initially add:

- Latinas in Tech - https://www.latinasintech.org/
- SHPE - https://www.shpeconnect.org
- LOFT Coder Summit - https://www.loftcsl.org/programs/loft-coder-summit/
- TECHNOLOchicas - https://technolochicas.org/
- ALPHA - https://www.alpfa.org/
- Latinx Founders Collective - https://www.latinxfounders.co/

See #294 for a similar request

**Comment by phurbalama** [comment]
Hi, fvcproduction
I would like to contribute to the project.

**Comment by fvcproductions** [comment]
@phurbalama You're more than welcome to! Let me know if you have any questions.
