### ISSUE TITLE
Create new resource page for "conferences"

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#343]
## Request

Let's add a page under resources located at https://techqueria.org/resources/conferences with the title "Conferences"

## Why did you make this request?

Let's showcase conferences that center around Latinx in Tech

## Any additional context?

Yes, here are a few conferences we would like to initially add:

- LULAC's Latinx Tech Summit: https://www.latinxtechsummit.org/home; https://www.latinxtechsummit.org/
- Latinx Tech Summit: http://www.latinotech.org/
- Latinx in Tech Summit: http://ltx-latinx-in-tech-summit.eventcreate.com/
- Latin Tech Summit: https://latintech.io/
- Latinx in AI Summit: https://www.latinxinai.org/events

See #294 for a similar request and how it was resolved in #323

**Comment by justjunior123** [comment]
Hi fvcproductions - Could I handle this issue? let me know if it is ok. Thanks!

**Comment by fvcproductions** [comment]
@justjunior123 yeah feel free!

**Comment by justjunior123** [comment]
@fvcproductions I've finished up the task locally and all looks great. Do I merge my changes? Sorry I'm new to open source and a little lost at the moment.

**Comment by hyerania** [comment]
@fvcproductions The conference category in resources is already part of the current site. All the links listed in this post have also been added on the site. This request seems to have already been completed. Is there anything else that needs to be done?

**Comment by fvcproductions** [comment]
@hyerania nope, not really - I will close

but I will create an issue to add in the images for resources without an image
