### ISSUE TITLE
New Content Update Request: Replace broken image link

### ISSUE THREAD

**Issue by phurbalama** [techqueria/website#345]
## Link where content currently exists

https://techqueria.org/press/

## Updates you'd like to make

The image link is broken for the first content that talks about undocumented immigrants

## Any additional context?

This was requested because...

**Comment by fvcproductions** [comment]
Looks like image is here: https://s.yimg.com/ny/api/res/1.2/8KKtdS3I_onGR3CwmWYsPA--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/http://media.zenfs.com/en/homerun/feed_manager_auto_publish_494/436ac184d2914cc291c4eec93a5355ae

So we just need someone to add this in locally.

**Comment by whimsicurl-creations** [comment]
I'm new to open source, but I would like to work on this if it is still open.
