### ISSUE TITLE
New Feature Request: Add Meetup events automatically

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#353]
## Request

Let's add events from our Meetup group to our Events page as cards automatically via their API

Meetup Group: https://www.meetup.com/techqueria/

## URL(s)

https://techqueria.org/events

## Why did you make this request?

We will never be able to add events to the website consistently so it's better if we take advantage of the platforms we use to create events and just add those in via their APIs.

## Any additional context?

Examples in the wild:

https://github.com/norfolkjs/norfolkjs.github.io
http://www.norfolkjs.org/
https://www.elastic.co/community/meetups
https://www.contentful.com/events/
http://www.techinmotionevents.com/events
https://www.galvanize.com/events
https://dribbble.com/meetups
https://www.framer.com/community/

**Comment by bote795** [comment]
basic research
meetups api allows to get the events i believe, this is an example with past events:
`https://api.meetup.com/2/events?&sign=true&photo-host=public&group_urlname=techqueria&status=past&page=20`

**Comment by bote795** [comment]
are we trying to add past or upcoming events or both?

**Comment by fvcproductions** [comment]
@bote795 both upcoming and past events would be great - you might be able to use fetch to get this data

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by bote795** [comment]
so this is how it currently looks just for past events. A lot of the meetup events don't have pics so yea..
https://gyazo.com/d8a12af2f5c146e4fc5f5c02212ac730
