### ISSUE TITLE
New Feature Request: Add Eventbrite events automatically

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#354]
## Request

Let's add events from our Eventbrite page to our Events page as cards automatically via their API

https://www.eventbrite.com/o/techqueria-san-francisco-13735914017

## URL(s)

https://techqueria.org/events

## Why did you make this request?

We will never be able to add events to the website consistently so it's better if we take advantage of the platforms we use to create events and just add those in via their APIs.

## Any additional context?

Examples in the wild:

https://github.com/norfolkjs/norfolkjs.github.io
http://www.norfolkjs.org/
https://www.elastic.co/community/meetups
https://www.contentful.com/events/
http://www.techinmotionevents.com/events
https://www.galvanize.com/events
https://dribbble.com/meetups
https://www.framer.com/community/

**Comment by bote795** [comment]
basic research 
https://www.eventbrite.com/platform/api#/introduction/authentication/getting-a-token
seems like Eventbrite requires login to be able to use their API to get events. So need a server or somewhere secure to get the token first then make the call 

meetups api allows to get the events i believe, this is an example with past events:
`https://api.meetup.com/2/events?&sign=true&photo-host=public&group_urlname=techqueria&status=past&page=20`

**Comment by fvcproductions** [comment]
@bote795 if there is no way to get events from just client side then we might need to close 🤔

**Comment by bote795** [comment]
yea based on my research we would need a server or some sort of lambda function or something since we need to get a token for a user and we need credentials for that and we don't want to put that in the client side.

**Comment by bote795** [comment]
well just read we could get a personal token if we create some random "qa-bot" account and try to see if we can use that to get the events? 

> Personal Tokens
As many of our API users are just doing an integration for a single user or organizer, we have a streamlined workflow for users to get an OAuth token just to represent themselves.All you need to do is visit your apps page, and make sure you have at least one app created. Every app you own will have a "Your OAuth Token" entry; click Show on that to reveal a premade OAuth token for your account.

want to try that approach @fvcproductions ?

**Comment by bote795** [comment]
Tested today with my account getting the personal token, (though this token does allow full control over the account I think I read somewhere, that's why I would say we would have to make a fake account and then use that token for that account) 
example of the api call 

upcoming events:
`https://www.eventbriteapi.com/v3/organizers/13735914017/events/?order_by=start_desc&status=live`

past events
`https://www.eventbriteapi.com/v3/organizers/13735914017/events/?order_by=start_desc&status=completed`

Do need to attach token to both requests 

Also, do we want both past and upcoming or?

**Comment by bote795** [comment]
also with the pr: #396  that adds meetup, how many of each or how would you wanna choose which one to display? @fvcproductions

**Comment by fvcproductions** [comment]
@bote795 in terms of how many, it doesn't matter too much - it can be all the events unless the response gets too big in the future (like 100+)

for future PR questions, feel free to ask in PR though 👍

**Comment by fvcproductions** [comment]
@bote795 Netlify does support server-side functions: https://www.netlify.com/docs/functions/

and we can take advantage of this since we have their pro plan/open source plan

https://www.netlify.com/pricing/#features

**Comment by bote795** [comment]
@fvcproductions haven't started a pr yet for this since I want to plan how we want this to work before I start implementing. 

>All Netlify sites include 125,000 serverless function requests per month, and 100 hours of run time per month. Above that, billing scales with your usage.

Do we get more than 125k requests to our website per month?

**Comment by fvcproductions** [comment]
@bote795 right now, we get no more than ~2,000 visits per month

**Comment by bote795** [comment]
@fvcproductions cool will start working on this after the meetup one goes through. 
Might have to do some changes in netlify to pass env variables, not sure how we handle the account and stuff. But I will wait on that until I get there.

**Comment by bote795** [comment]
@fvcproductions have started on this pr, but need to add some env variables in netlify.
wanted to do the second or third bullet point mentioned here https://www.netlify.com/docs/continuous-deployment/#environment-variables

> In your site dashboard under Settings > Build & deploy > Environment > Environment variables. Variable values set under site settings will override the team-level settings.
In team settings, under Settings > Sites > Global site settings > Shared environment variables. Variables set at the team level are shared by all sites owned by the team. These can be overridden by settings at the site level. (This feature may not be available on all plans.)

Do we have team settings? have a local instance working but need to test to see if non-local stuff works. But need the env variable set and then I should be able to just open the pr to test it via preview?

**Comment by fvcproductions** [comment]
@bote795 apologies for delay but if u DM me your email, I can add u as a collaborator so you can add in env variables

https://app.netlify.com/teams/techqueria/members/new

**Comment by fvcproductions** [comment]
Closing for now - see #478
