### ISSUE TITLE
New Resource Request: TheBestSchools.org 

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#356]
## Name & Description

Hi there, 
  
The education of the youth population has a direct impact on the wellbeing of its economy, health, and prosperity. This holds true around the nation; however, roughly 65,000 undocumented immigrants graduate from high school each year, and only  10,000 enroll in college. In addition, even fewer that that graduate, despite the numerous resources available to help these students. 
  
To lift up this population, and all our communities in turn, TheBestSchools.org has curated a series of open-use guides dedicated to fostering undocumented, academic collegiate success. These guides contain a bounty of information for undocumented students on core topics including financial aid, student and constitutional rights, DACA legislation, and more sources of legal support and advocacy. 
 
College Guide Series for Undocumented Students 

College Success Guide -  https://thebestschools.org/resources/undocumented-students-guide-college/ 

College Protections -  https://thebestschools.org/resources/colleges-protect-undocumented-students/ 

Knowing Your Rights -  https://thebestschools.org/resources/undocumented-students-rights/ 

Advocacy and Support -  https://thebestschools.org/resources/undocumented-students-advocacy-support/ 

DACA and Key Legislature -  https://thebestschools.org/resources/undocumented-students-daca-laws/ 

Financial Aid Guide -  https://thebestschools.org/resources/undocumented-students-financial-aid/ 

Best Colleges Ranking -  https://thebestschools.org/resources/colleges-undocumented-students/ 

Online College Options -  https://thebestschools.org/resources/undocumented-students-online-college-guide/ 

The information presented in these guides can start a student well on their path to success, but not all are aware of the opportunity.  Please help us reach students by posting links to these guides on the Techqueria website, here for instance - https://techqueria.org/resources/career/ - Your link will be a great help to our academic communities. 
  
Thank you for your effort in sharing these educational materials. Please reach out to us with any questions you may have. 

Emma Anderson | AndersonEmma@thebestschools.org 
Marketing and Communications Outreach | TheBestSchools.org 
PO Box 524314 | Houston, TX 77052 |  Facebook |  Twitter 

TheBestSchools.org is an independent organization comprised of a dedicated group of educators, professionals, and authors providing the best resources and advice to assist learners through every step of their education, into their careers, and toward sustainable lifelong learning. Learn more about us, if you do not want to receive emails from us in the future, please reply to this message with "Remove" in the subject line.  

## Category

Students

## Desired Slug

https://techqueria.org/resources/students/best-schools

**Comment by cyberfernandez** [comment]
@fvcproductions I would like to be assigned for this issue #356 if possible? I would like to complete this! :)

**Comment by fvcproductions** [comment]
Closing for now
