### ISSUE TITLE
Update sponsor list

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#36]
Currently sponsors are listed as a bulleted list with a short description following.
As the list of sponsors grows, this will become a wall of text. Also, this description format works well for smaller companies that are lesser known, but seems a bit weird describing larger companies that are more popular like Google. 

One idea is to create a sprite with company logos

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by mvargasvega** [comment]
@fvntr Let me send you screenshot of what I think you are looking for. 

What if we just put the logos of the company, and if the user hovered over the logo, a small description would pop up. Then if they were to click on the logo, it would send to the respective organization.

**Comment by fvntr** [comment]
<img width="922" alt="screen shot 2018-09-15 at 12 48 50 am" src="https://user-images.githubusercontent.com/1316570/45584045-941caf80-b881-11e8-8182-ca0be52b250b.png">

**Comment by fvcproductions** [comment]
I actually addressed this in PR #39 - see https://deploy-preview-39--techqueria.netlify.com/sponsors/ for a preview of what the new layout would like.

We still need to add the other sponsors though which can be done in a future PR. 😄

**Comment by db118** [comment]
@fvcproductions Is this still up for grabs 👀

**Comment by fvcproductions** [comment]
Done!
