### ISSUE TITLE
New Feature Request: Add Google Calendar to events page

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#367]
## Request

Add the following

```
You can also [subscribe to our Google Calendar](https://calendar.google.com/calendar/embed?src=dvidsilva.com_eieh0fli3i3nheb8j8naav4tco%40group.calendar.google.com&ctz=America%2FLos_Angeles) to keep track of events or get more involved as a local organizer/volunteer.
```

## URL(s)

https://techqueria.org/events

Add right after "See all our events on Eventbrite or Meetup."

## Why did you make this request?

Get more folks aware of Techqueria events

## Any additional context?

N/A

**Comment by Ania-chan** [comment]
Hi! I'm very new to the open source and I'd like to work on this issue!
