### ISSUE TITLE
New Feature Request: Add new Patreon Supporter

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#372]
## Request

Add new supporter to Patreon Supporters page

$25 supporter

Giovanni Bryden

Principal Sales Engineer at Mixpanel

https://www.linkedin.com/in/giovanni-b-8a822952/

## URL(s)

https://techqueria.org/patreon-supporters

## Image

https://avatars1.githubusercontent.com/u/2127351?s=460&v=4

## Why did you make this request?

Each Patreon supporter gets highlighted on the website

## Any additional context?

N/A

**Comment by l3njo** [comment]
I'll work on this

**Comment by nathantomsfairsailcom** [comment]
Hi, I am new to OSS contributions and would like to give this one a go
