### ISSUE TITLE
New Resource Request (Multiple)

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#378]
1. https://futureforus.co/ - add to a new Latinas resource category
2. https://wallbreakers.com/ - students
3. https://svlatino.com/ - Career
4. https://www.techhireoakland.org/ - Career
5. https://zapier.com/blog/best-nonprofit-discounts/ - Nonprofits

**Comment by PoseidonSigmaX** [comment]
Hey, I'd like to work on this, which file do I need to add it to though? @fvcproductions

**Comment by fvcproductions** [comment]
@PoseidonSigmaX I updated the contributing guidelines for more context here - the categories are mentioned in the initial issue but let me know if you have any questions! 👍 

https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md#resources
