### ISSUE TITLE
Consolidate blog

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#38]
https://blog.techqueria.org/ could be located on the website without it being an external link

This is up for discussion as it's not required but since the blog only has a few posts now, it might be worth just moving it all to the main website so its gets higher ranked in search results

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvntr** [comment]
I think this is a great idea. How were you thinking? I'd still like to use medium.

**Comment by fvcproductions** [comment]
Medium is great but the site would get more traffic since the blog posts are all hosted in the same place.

It also allows for more customization like an email newsletter section at the bottom of every blog post.

We could also automate the sharing of blog posts and events so that anytime there is a new one created, it will take the updated RSS feed and can share to Twitter, Facebook, LinkedIn, etc.

**Comment by fvcproductions** [comment]
Users are also more likely to explore rest of Techqueria website since they are not leaving the site for Medium.

**Comment by YourMobileGeek** [comment]
@fvcproductions @fvntr I recently heard about this site generator called Gatsby that's great for making starter blog if we decide to navigate away from Medium 

[https://github.com/gatsbyjs/gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog )

[https://medium.freecodecamp.org/how-to-build-a-react-and-gatsby-powered-blog-in-about-10-minutes-625c35c06481](https://medium.freecodecamp.org/how-to-build-a-react-and-gatsby-powered-blog-in-about-10-minutes-625c35c06481)

**Comment by fvcproductions** [comment]
@YourMobileGeek Hugo works great for this as well and we can bake it right in! 😄 

@dvidsilva Would you be okay with us making this transition from Medium to self hosted on https://techqueria.org? What are your thoughts on this? 

If it's cool, I think we should move forward with copying existing blog posts and transferring them to https://techqueria.org.

**Comment by fvntr** [comment]
lets migrate the existing blog posts @fvcproductions

**Comment by fvntr** [comment]
closing this
