### ISSUE TITLE
New Feature Request: Unified Social Button Design in Top Nav

### ISSUE THREAD

**Issue by ghost** [techqueria/website#402]
Hi, just wanted to make a suggestion for the social buttons in the Top Nav.
  
## Request

Let's add...

I'm suggesting that the social icons use a unified icon design for social button (ex: all rounded with the same color/hover-highlight effect).  

Icons:
 - LinkedIn
 - Twitter
 - Slack
 - Login

## URL(s)

https://techqueria.org/

## Why did you make this request?

Just want to get involved in new projects.

## Any additional context?

Mobile view includes slack and login buttons, but desktop view does not.  May consider adding an issue for the lack of a login button in desktop view.

**Comment by fvcproductions** [comment]
No longer relevant as we don't show Slack buttons on desktop
