### ISSUE TITLE
New Content Update Request: Add images for resource pages

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#408]
## Link where content currently exists

https://techqueria.org/resources

## Updates you'd like to make

Any resources that don't have an image should have an image added

For example: https://techqueria.org/es/resources/conferences/

## Any additional context?

Nope, you basically just need to add images - it's an easy win!

**Comment by Sol1323** [comment]
@fvcproductions I would love to work on this issue [#408](https://github.com/techqueria/website/issues/408) if it is possible. More than happy to contribute to Techqueria's website.

**Comment by fvcproductions** [comment]
@Sol1323 I just assigned you to this issue - let me know if you have any questions! 💯

**Comment by Sol1323** [comment]
@fvcproductions Great, thank you! Will keep you posted of any updates or questions.

**Comment by Sol1323** [comment]
@fvcproductions PR [#416 ](https://github.com/techqueria/website/pull/416) for this issue is ready for review. I will be available by all means, loved contributing here.
