### ISSUE TITLE
Update image dimensions for Open Graph images in header

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#42]
Insert description of issue here
Showcase the embedded or `og` image full size
http://ogp.me/

https://developers.facebook.com/docs/sharing/webmasters/

https://opengraphcheck.com/---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
Relevant file: https://github.com/techqueria/website/blob/master/site/layouts/partials/head.html

**Comment by fvcproductions** [comment]
Should look something like this across all social media platforms/Slack embeds (already looks like this for Twitter).

<img width="463" alt="screenshot 2018-09-19 12 56 06" src="https://user-images.githubusercontent.com/4284691/45777711-734eb400-bc0b-11e8-8344-218b2e01ce95.png">

**Comment by fvcproductions** [comment]
Verified on Facebook - turns out it just needed to be scraped again!

![screenshot 2018-09-27 19 39 19](https://user-images.githubusercontent.com/4284691/46185009-0c756e80-c28d-11e8-808e-2a310a38faf2.jpg)
