### ISSUE TITLE
Update homepage image (?)

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#43]
The current homepage image seems a bit older and lower resolution - might be worth exploring adding a newer high-res image from a recent Techqueria event. 

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by YourMobileGeek** [comment]
I can help out with switching out the homepage image! Has an high-res image been selected yet?

**Comment by fvcproductions** [comment]
@dvidsilva Do you have a preference? Otherwise, I can choose one from the stock photos we have?

@YourMobileGeek Thanks so much for volunteering to do this! 😄

**Comment by dvidsilva** [comment]
None preference @fvcproductions

**Comment by fvcproductions** [comment]
@dvidsilva Thinking maybe a hero carousel would be cool but I like 

https://drive.google.com/open?id=1inzalQW1ZfXLJrLbHXn0tJhoansGw5Ho

I am also trying to get pictures from the Oakland event to see if there's any good group photos from there. 😄

**Comment by dvidsilva** [comment]
@fvcproductions that one is beautiful we can crop the top and bottom a little maybe. 

I don't love carousels, but if you think that's a good idea go for it

**Comment by YourMobileGeek** [comment]
@dvidsilva @fvcproductions Just submitted a pull request for this issue: #108
