### ISSUE TITLE
New Feature Request: Referrals

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#431]
## Referrals

https://techqueria.org/referrals
https://techqueria.org/refer

- Should be public-facing in case allies want to let their Latinx friends know about it
- Sends email to the friend inviting them to sign up
- example: https://communitybot.co/?ref=producthunt

**Comment by vtostado** [comment]
Hi, I'd like to work on this if it's still open. Can I get more information about this feature :D

**Comment by fvcproductions** [comment]
@vtostado hey - yeah basically we just want an easy way for people to refer others to become a member to the techqueria community

i was thinking for a v1, it could just be a landing page at https://techqueria.org/refer on the benefits of being a member and then showing them where to sign up

in the meantime, i have https://techqueria.org/refer redirecting to https://techqueria.org/join
