### ISSUE TITLE
Bug: Events Meetup

### ISSUE THREAD

**Issue by bote795** [techqueria/website#445]
## What's going on?
The Events Meetup display isn't updating. 

## How can we reproduce this bug?

1. Go to https://techqueria.org/events/meetup/
2. See that it still shows a past event.

## What is the expected behavior?

It shouldn't show an event that has already passed in the upcoming event section 

## Any screenshots?

[![Image from Gyazo](https://i.gyazo.com/8e2282e1ca1c39388200dd53c1730964.png)](https://gyazo.com/8e2282e1ca1c39388200dd53c1730964)

## What is your environment?

macOS High Sierra, Chrome 26.11

## Any additional context?

I just realized why, with my low knowledge of Hugo, how it was created using their API's, makes it so that it only creates the events when the server spins up. So essentially it took the snapshot from the API created the templates for the events. But every time you visit it doesn't do a new call. So just need to re-write to be javascript on the client-side instead of using Hugo. 

#353

**Comment by fvcproductions** [comment]
Closing this for now - going to move forward with not importing events from Meetup & Eventbrite for now
