### ISSUE TITLE
Find a way to display partner events separate of official events

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#45]

**Comment by fvcproductions** [comment]
Yeah, we can include a partner event boolean to be in the front matter.

`partnerEvent: true` which would then add a line in the card noting it's a partner event somehow.

**Comment by fvntr** [comment]
can we do this for the event on the calendar as well?

**Comment by darrylbalderas** [comment]
Maybe a taco emoji to distinguish partner events from official events 🤔. I'm not quite sure.
<img width="764" alt="screen shot 2018-10-22 at 7 06 49 pm" src="https://user-images.githubusercontent.com/10657206/47330658-e34ac280-d62d-11e8-9a47-ce78fcfe97b5.png">

<img width="1325" alt="screen shot 2018-10-22 at 6 48 36 pm" src="https://user-images.githubusercontent.com/10657206/47330659-e5148600-d62d-11e8-9c23-be76b77ef93e.png">

**Comment by fvntr** [comment]
Yeah that works for now but most of these events are hosted by us anyways. 
The events that aren't already have other company's logo as part of the event advertisement. 
Is this really an issue? I'm inclined to close unless we have received feedback to the contrary 
@fvcproductions @dvidsilva thoughts?

**Comment by fvntr** [comment]
An easy way to fix this is to only have Techqueria hosted events on the events page
And we can put events organized by other organizations as part of the calendar

**Comment by fvcproductions** [comment]
I think it's worth differentiating but I also think it's a lower priority issue. 

If I had the bandwidth, I would just add the front matter variable from earlier so that if it's true, it would add text ("Partner Event: ") in the title so partner events just had "Partner Event: XYZ" as the title.
