### ISSUE TITLE
New Feature Request: Set up publications like companies are set up

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#454]
We would like to set up the publications so we can display them in a cool way like the companies are right now.

https://techqueria.org/support-us/supporters

so there should be something like

https://techqueria.org/press/publications but showcasing the publications we've been featured in instead

**Comment by Torden360** [comment]
Hi, I have begun work on this. Are there publications on the website currently?

**Comment by fvcproductions** [comment]
@Torden360 thanks for your patience

so the way I was envisioning this was having the publications that are from https://techqueria.org/news and showcasing it in a flexbox way like on https://techqueria.org/supporters

ergo the publications would just be showcased in cards and then be added in on the news page in a separate section labeled "Featured Publications"
