### ISSUE TITLE
New Content Update Request: Spanish translations for https://techqueria.org/slack

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#456]
## Link where content currently exists

https://techqueria.org/slack

## Updates you'd like to make

Spanish translations needed for updated material

## Any additional context?

N/A

**Comment by mariajose13** [comment]
I will be willing to help

**Comment by rcuesta00** [comment]
Hi,

I see task as stale, but if you need more help with this, I offer myself to the job.

Best.

**Comment by KGmajor** [comment]
@techqueria/website-admins would be able to update the assignee here @rcuesta00!

**Comment by fvcproductions** [comment]
Done!

**Comment by LuisPinedaJR** [comment]
Hello,
I see this request is still open and stale, I’d be happy to help with translations 🙂

**Comment by fvcproductions** [comment]
> Hello,
> I see this request is still open and stale, I’d be happy to help with translations 🙂

Yes feel free!

**Comment by LuisPinedaJR** [comment]
added a couple of changes  https://techqueria.org/slack

**Comment by fvcproductions** [comment]
This was resolved in #637
