### ISSUE TITLE
New Resource Request: Add Twitter SF event 

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#469]
## Name

Add the following event details to the event page: http://twitterthreadswithtechqueria.splashthat.com

## Description

This will be the next SF event with Twitter

## Link to Resources

http://twitterthreadswithtechqueria.splashthat.com

## Desired Slug (optional)

https://techqueria.org/category/slug

**Comment by fvntr** [comment]
the link is on the site already, it just needs to be updated

**Comment by veegee2k17** [comment]
I can take this!

**Comment by fvcproductions** [comment]
@veegee2k17 I already had a PR going so I went ahead and added the link - thanks for being willing to jump in! 🙏🏽
