### ISSUE TITLE
Bug: Footer Social Icons incorrect link

### ISSUE THREAD

**Issue by phcarbajal** [techqueria/website#476]
## What's going on?

The links at the footer of the webpage does not link right correctly:
Facebook -> Instagram
Instagram -> Twitter

## How can we reproduce this bug?

Go to Techqueria.org and scroll all the way down.

## What is the expected behavior?

Link:
Facebook -> Facebook
Instagram -> Instagram

## Any screenshots?
When highlighting facebook:
<img width="716" alt="facebook- instagram" src="https://user-images.githubusercontent.com/35918666/62824624-a1a3ed80-bb55-11e9-8bf1-56a7ab8c9570.png">

when highlighting twitter:
<img width="536" alt="instagram- twitter" src="https://user-images.githubusercontent.com/35918666/62824625-a5377480-bb55-11e9-8f53-be7844aca956.png">

## What is your environment?

macOS High Sierra, Chrome 26.11

## Any additional context?

No

**Comment by fvcproductions** [comment]
@phcarbajal oopsies - that was my bad - see #477 for fix

**Comment by phcarbajal** [comment]
Why do I need to have Hugo installed to see the changes to the href? Everything seems to have worked when using my local machine except this one thing.
