### ISSUE TITLE
New Feature Request: tracking data from donations

### ISSUE THREAD

**Issue by BelenGiraudo** [techqueria/website#479]
## Track Techqueria donations.

Edit the page that has a donation form on it and add the following code inside an Unformatted Text part. While editing the Unformatted Text part, select Show Advanced Options and choose at the end of the <body> tag from the drop down menu and add this code:

<script type="text/javascript">
   BLACKBAUD.netcommunity.api.DonationConfirmation.add(function (data) {
       if (data.TransTotal) {
                                               var items=[];
                                               var dataItem;
                                               for (var i = 0; i < data.Items.length; i++) {
                                                               dataItem={};
                                                               dataItem.id= data.Items[i].ID;
                                                               dataItem.name = data.Items[i].Name;
                                                               dataItem.list_name = '',
                                                               dataItem.brand='',
                                                               dataItem.category= data.Items[i].Name;
                                                               dataItem.variant='',
                                                               dataItem.list_position=i+1;
                                                               dataItem.price= data.Items[i].Price;
                                                               dataItem.quantity= data.Items[i].Quantity;
                                                               items.push(dataItem);
                                               }
                                               gtag('event', 'purchase', {
                                                                                                               "transaction_id": data.TransID,
                                                                                                               "affiliation": '',
                                                                                                              "value": data.TransTotal,
                                                                                                               "currency": '',
                                                                                                               "tax": '',
                                                                                                               "shipping": '',
                                                                                                               "items": items
                                                                                               }
                                                               );
                               }
   });
</script>

## URL

https://techqueria.org/xyz

## Why did you make this request?

Track donations to see where they come from and how to increase them.

**Comment by fvcproductions** [comment]
Going to close this since we want to move forward using Netlify Analytics https://www.netlify.com/products/analytics/ instead of loading more JS
