### ISSUE TITLE
New Feature Request: Advertising Techqueria in Latin countries

### ISSUE THREAD

**Issue by BelenGiraudo** [techqueria/website#481]
## Advertising Techqueria

I have discovered through google analytics that 89% of people who engage with techqueria live in the U.S. and I was thinking that we could get people from other latin countries engaged through facebook, linkedin and through any other social media, to get more people connected and more donations too.

## URL(s)

https://techqueria.org/xyz

**Comment by fvcproductions** [comment]
We have already have https://techqueria.org/es which is the site translated in Spanish. The translations are not always up to date but we are also prioritizing efforts in the US right now 

Thanks for opening this issue!
