### ISSUE TITLE
New Feature Request: Adding information to Techqueria's main page

### ISSUE THREAD

**Issue by BelenGiraudo** [techqueria/website#482]
Adding information to Techqueria's main page

There is a bounce rate of 61%, which means that 61% of people who open Techqueria's webpage, closes it with no interaction. I would suggest explaining how does techqueria serve the largest community of Latinx in Tech in the main page to get more people engaged. By adding more information explaining how the company serves the largest community of Latinx in Tech, we can get more people to join techqueria, to engage and to donate too.

## URL(s)

https://techqueria.org/xyz

## Why did you make this request?

So that people would engage more with Techqueria.

**Comment by fvcproductions** [comment]
we can add some sections on the HP in to help with this - i agree there could be more content on HP

- donate section
- about section

**Comment by fvntr** [comment]
Hey Eduardo just assigned this to you!
Feel free to ask any questions you may have here
