### ISSUE TITLE
Update About Page to reflect current organizers

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#53]
The current about page doesnt reflect people currently organizing.
Also we should consider adding an 'alumni' or past organizers section as a way of showing our appreciation for their work. 
---

> ✅️ By submitting this issue, I have verified the following

* [x ] Checked to see if the issue has already been discussed before 🤔️
* [ x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
This is just a simple Markdown file update so feel free to take this on!

**Comment by fvntr** [comment]
please assign to me

**Comment by fvntr** [comment]
https://github.com/techqueria/website/pull/71
