### ISSUE TITLE
New Resource Request: Add Appdynamics event

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#531]
Add the following event: https://www.eventbrite.com/e/abstract-techqueria-and-latinas-in-techs-vida-latina-tickets-70580077913 to events

## Link to Resources

https://techqueria.org/events/

**Comment by danielharvilik** [comment]
Hello, is this still available ?

**Comment by lomeli-noe** [comment]
@fvntr the link you provided is for Abstract, Techqueria and Latinas in Tech's Vida Latina and it expired last month.  Is the event for appdynamics listed here: https://www.appdynamics.com/events/ ?

**Comment by fvcproductions** [comment]
hey folks - we add past events to https://techqueria.org/events - if you take a look at the page you can see how we link the pages

**Comment by fvcproductions** [comment]
added this in #530
