### ISSUE TITLE
New Resource Request: Add September Techqueria NYC events

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#535]
https://www.eventbrite.com/e/hispanic-heritage-kick-off-perreo-tickets-71424704213
https://www.eventbrite.com/e/panel-being-latinx-in-the-music-industry-tickets-71922808055
https://www.eventbrite.com/e/pala-comunidad-techs-impact-on-the-latinx-community-tickets-73060691495

## Description

Add to https://techqueria.org/events/

**Comment by fvcproductions** [comment]
being addressed in #551

**Comment by cjoshmartin** [comment]
@fvcproductions should this be closed?

**Comment by fvcproductions** [comment]
Yep! Will close now.
