### ISSUE TITLE
New Resource Request: Add ATX meetup to site

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#538]
Add https://www.eventbrite.com/e/techqueria-meet-up-tickets-62657254535 to techqueria.org/events

**Comment by migben** [comment]
can we close this issue? It seems the event has already ended.

**Comment by fvcproductions** [comment]
@migben we include past events on techqueria.org/events

**Comment by scarlettperry** [comment]
@fvntr @fvcproductions have started to work on this.
