### ISSUE TITLE
Create a CFP (call for proposals)

### ISSUE THREAD

**Issue by technomoda** [techqueria/website#54]
Example: http://techintersections.org/call-for-speakers/proposals/

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [ ] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
WaffleJS was mentioned in Slack and the way they do it is via GitHub issues. Is that the way we want to do it too?

https://wafflejs.com/

There's also Google Forms.

**Comment by fvcproductions** [comment]
@technomoda created a Google Form for this - can you link this so we get this added in? 😄

**Comment by fvntr** [comment]
Yes I will take care of this. Where do you think the best place to add it is?  @technomoda

**Comment by technomoda** [comment]
Hey @fvntr 
Ideally I'd like to have it on the nav bar, top right. 
Move the Sponsor link to the right so it's not on there twice. 
Is there a difference between sponsors and hosts? 
Also can we bring the <p>, and menu link font size to something smaller like 16px?

What do you think of this? 
*the twitter and fb buttons can be moved to the bottom for now, maybe
<img width="603" alt="screen shot 2018-10-16 at 3 47 58 pm" src="https://user-images.githubusercontent.com/11223564/47051841-e55ae000-d15a-11e8-808c-ff8170eac6ad.png">

**Comment by fvntr** [comment]
I like that this call to action is one of the first things that a person sees on the page
How would you include it on a smaller screen size (attached for reference) 

<img width="325" alt="screen shot 2018-10-16 at 22 02 23" src="https://user-images.githubusercontent.com/1316570/47063248-34bb0380-d18f-11e8-9826-9ea9841f7d2f.png">

**Comment by technomoda** [comment]
<img width="284" alt="screen shot 2018-10-17 at 2 12 11 pm" src="https://user-images.githubusercontent.com/11223564/47116634-07199d00-d217-11e8-852a-d289d29c7c17.png">
<img width="283" alt="screen shot 2018-10-17 at 2 12 19 pm" src="https://user-images.githubusercontent.com/11223564/47116635-07199d00-d217-11e8-8d15-1fb77a8b927e.png">

What do you think about this? @fvntr

**Comment by fvntr** [comment]
we would need two additional forms for host and sponsor

**Comment by fvntr** [comment]
the design looks good though, I like that yellow

**Comment by fvntr** [comment]
will tackle this and #172 in parralel
