### ISSUE TITLE
New Resource Request: Add SF October Events

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#543]
#8# Description
Add 10/9 event and 10/17 event to site under events

## Link to Resources

https://techqueria-crunchbase-eng-dinner.splashthat.com/
https://latinxinproduct.splashthat.com/

## Category

Insert category here

## Desired Slug (optional)

https://techqueria.org/category/slug

**Comment by scarlettperry** [comment]
Hi @fvntr! I'd like to work on this if this would still be helpful for your team.

**Comment by fvcproductions** [comment]
@scarlettperry Feel free to work on this - I can provide feedback or answer any questions

**Comment by fvcproductions** [comment]
@scarlettperry feel free to work on the other event issues - i went ahead and handled this one since i had the assets ready - check out #537 or #536 or #538

**Comment by scarlettperry** [comment]
@fvcproductions will do! can you assign me to do the other event issues?
