### ISSUE TITLE
Translation Issue: Create a Spanish version for README.md

### ISSUE THREAD

**Issue by pedrorufino** [techqueria/website#547]
## Context
Create a README file in Spanish could make the project more accessible for non-english speakers. 

## Acceptance Criteria
:black_square_button: Make sure README document have English and Spanish versions.

**Comment by meda123** [comment]
Hi! I would like to volunteer with this translation! Let me know if I can start.

**Comment by pedrorufino** [comment]
Go ahead  😊

**Comment by AngelsProjects** [comment]
I can do it right now 👍
