### ISSUE TITLE
Different card image height in communities and sponsor page

### ISSUE THREAD

**Issue by darrylbalderas** [techqueria/website#56]
An example of difference of card image height in sponsor page
![screen shot 2018-09-20 at 11 45 36 pm](https://user-images.githubusercontent.com/10657206/45864694-ad18db00-bd2f-11e8-955a-277f4b4dd746.png)

Another example in difference of card image height in communities page

![screen shot 2018-09-20 at 11 46 24 pm](https://user-images.githubusercontent.com/10657206/45864736-d33e7b00-bd2f-11e8-9fce-566a830cace2.png)

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [ ] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
See https://bulma.io/documentation/elements/image/
