### ISSUE TITLE
Sponsor logos are inconsistent

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#58]
Sponsor logos are taking up the dimensions of parent container and is causing some logos to look off. 

---

> ✅️ By submitting this issue, I have verified the following

* [x ] Checked to see if the issue has already been discussed before 🤔️
* [x ] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by db118** [comment]
Is it possible to give me a visual representation of the issue 😄 ?

**Comment by fvcproductions** [comment]
Refer to #57 and current sponsor pages

**Comment by fvcproductions** [comment]
This was reverted but there's still a desire to use background image instead for perspective.

**Comment by fvcproductions** [comment]
Further discussion will take place in #56 and I believe that @db118 is already working on making this look more optimal.
