### ISSUE TITLE
New Content Update Request: City Chapter Learn More Button should be Join Us

### ISSUE THREAD

**Issue by briantrejo1** [techqueria/website#581]
## Link where content currently exists
All city chapter pages under https://techqueria.org/communities/chapters/

## Updates you'd like to make
The "Learn More" button copy should change to "Join Us" 
On click, "Join Us" button should redirect visitors to https://techqueria.org/join/#apply-to-become-a-member

## Any additional context?
This was requested because we had a new visitor google "techqueria atlanta" and landed on that page. When they clicked 'learn more' to access the Atlanta channel, it put them in front of a general slack login page.

<img width="1243" alt="Screen Shot 2019-11-18 at 9 11 51 PM" src="https://user-images.githubusercontent.com/3301282/69110240-12598080-0a48-11ea-977f-02c115532b3b.png">

**Comment by WilliamMena** [comment]
@briantrejo1 I noticed that each of the links redirect to a specific slack channel for each city. I agree on the text change to 'Join Us' but I believe adjusting the redirect would change the original intent of this page. 

What do you think @fvcproductions

**Comment by fvcproductions** [comment]
Yeah, these are good points! I ended up changing it to the chapter page on our new events platform

ergo SF Chapter page would have https://events.techqueria.org/san-francisco-bay-area/ as link and so on and so forth
