### ISSUE TITLE
New Feature Request: Add stats to homepage

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#584]
## Request

Let's add stats front and center to HP

i.e. 8,000+ members 10+ cities 3+ countries 5 chapters, etc.

## URL(s)

https://techqueria.org/

## Why did you make this request?

Numbers = big impact

**Comment by sureshmangs** [comment]
I want to take the issue
Where do you want to display the stats on the homepage?

**Comment by cjoshmartin** [comment]
How can I help? What stats would you like to add?

**Comment by fvcproductions** [comment]
Sure @cjoshmartin 

Stats are as follows

8,250+ members
5 cities
75+ events
15K+ user reach on social media

Here's some inspiration for layout

![Screen Shot 2020-01-04 at 11 38 34 PM](https://user-images.githubusercontent.com/4284691/71776783-aecdd880-2f4b-11ea-8981-5d0d3cf4f5aa.jpg)
![Screen Shot 2020-01-04 at 11 38 41 PM](https://user-images.githubusercontent.com/4284691/71776784-aecdd880-2f4b-11ea-9873-ea30f31e91e8.jpg)

**Comment by fvcproductions** [comment]
I think a simple 4 column component on the homepage should be good

**Comment by cjoshmartin** [comment]
@fvcproductions Would the data be static or dynamic?

**Comment by fvcproductions** [comment]
It would be static so as not to affect performance substantially for the homepage which is valuable real estate.
