### ISSUE TITLE
Create a 'latinxs in tech' album collection with stock images 

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#6]
Similar to this
https://jopwellcollection.jopwell.com/thejopwellcollection/  

or this
https://www.wocintechchat.com/blog/wocintechphotos

It would be great to have an album of our events, hackathons, startup weekend, etc. So that people can have some images to use for their events or websites meant for latinxs in tech.

**Comment by fvcproductions** [comment]
I'm definitely not a professional photographer but what could help streamline this process is just crowdsourcing this and making it a fun thing - ergo, if you have a professional photo that you want to share, then we consolidate them all in an album and have them available through the website.

Maybe a message in random to gather photos?

Just some thoughts. ¯\_(ツ)_/¯

**Comment by dvidsilva** [comment]
I'm gonna add links here to albums we have, and we can think of a cool way to organize them and also decide like what type of license are we going to allow.

https://photos.app.goo.gl/Rv4E4H7RRkYbAQJz7

**Comment by fvcproductions** [comment]
I vote for PassGallery: https://passgallery.com/pricing - it's $0 for up to 20 GB of storage.

**Comment by fvcproductions** [comment]
Or maybe some way to just embed directly onto website?

**Comment by fvcproductions** [comment]
There's also Flickr and potentially embedding Google Photos onto website.

Also, for the NYC photos, those should be transferred to a Google Photos album.

I think I prefer keeping all the photos in the Google Photos albums so it's less work.

We should just set guidelines on CC and photo album titles. 👍

**Comment by fvcproductions** [comment]
I think it should be non-commercial usage: https://www.flickr.com/creativecommons/

**Comment by fvcproductions** [comment]
And then they can pay if they want to use it?? But that would require an e-commerce integration... I dunno.

**Comment by fvcproductions** [comment]
This was done so I will close and create a separate issue for Startup Weekend Latinx NYC 2018 event
