### ISSUE TITLE
Add Latinx in Design somewhere

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#63]
It would be great to add https://www.latinxswhodesign.com somewhere to support our Latinx Designers.

This is just a suggestion though.

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvntr** [comment]
I can take this please assign

**Comment by fvcproductions** [comment]
@dvidsilva I think in order to have @fvntr assigned, he needs to be a contributor or GitHub settings need to be changed - not sure.

**Comment by dvidsilva** [comment]
@fvcproductions just added him to the org

**Comment by fvntr** [comment]
https://github.com/techqueria/website/pull/70
