### ISSUE TITLE
New Content Update Request: 

### ISSUE THREAD

**Issue by emmazunz** [techqueria/website#662]
## Link where content currently exists

https://techqueria.org/team/

## Updates you'd like to make

i should still be listed as a chapter director for austin

## Any additional context?

i'm not sure why i was removed, as i'm still an active CD in austin.

**Comment by fvcproductions** [comment]
Hey Andrea, I did this after I heard you were moving but I can revert the change, it's just adding in the role on ur page

**Comment by emmazunz** [comment]
yeah, i'm still doing CD work here. please revert.

**Comment by fvcproductions** [comment]
Ok the issue has to be open, once the fix is in, then we can close

**Comment by emmazunz** [comment]
👍🏽thanks. will let you know when i'm no longer doing work in austin/the CD title can be rm-ed.

**Comment by fvcproductions** [comment]
https://github.com/techqueria/website/commit/93fcbff010b8dbbe520b63c3d02f49f0ec31071c

updated
