### ISSUE TITLE
New Feature Request: Triplebyte referral link 

### ISSUE THREAD

**Issue by marieram** [techqueria/website#673]
## Request

Let's add the referral link  https://triplebyte.com/a/Wergxwo/d to the community partner: triplebyte section located here https://techqueria.org/supporters/

## URL(s)

https://techqueria.org/supporters/

## Why did you make this request?

I need this to finish the deliverables for our contract with Triplebyte.

## Any additional context?

This needs to be...

**Comment by fvntr** [comment]
Addressed with https://github.com/techqueria/website/pull/680
