### ISSUE TITLE
New Content Update Request: Latinx Therapy

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#698]
Address the following: 

"Hello- We are redoing our site and have come across the link above. We noticed that our logo is being used but with the wrong URL. Can you please either adjust the URL and title to Latinx Therapy, as we do provide online and in-person services in individual and group format, pro bono work as well, or please replace the logo to reflect Therapy for Latinx? I understand this may have been an oversight as the names are similar." 

correct org name: Latinx Therapy
correct link: www.latinxtherapy.com

**Comment by fvcproductions** [comment]
Removing them in #701 - they can be added back
