### ISSUE TITLE
Create a standard version of the logo to use in places

### ISSUE THREAD

**Issue by dvidsilva** [techqueria/website#7]
Change on the following places: 

- [x] website
- [x] facebook group
- [x] facebook page
- [ ] SF twitter
- [ ] NY twitter
- [ ] LA twitter
- [ ] instagram 
- [ ] NY instagram
- [ ] youtube
- [x] github

**Comment by fvcproductions** [comment]
As of June 13, 2018 - this is how all the social media accounts look like for Techqueria. This is for reference and can help us decide which logo we can use as our standard.

# Meetup

> 2,124 members

<img width="1703" alt="screenshot 2018-06-13 19 32 19" src="https://user-images.githubusercontent.com/4284691/41388390-926a7670-6f40-11e8-8523-615f9cd6a4ac.png">

# Facebook

> 1,386 members

<img width="826" alt="screenshot 2018-06-13 19 30 20" src="https://user-images.githubusercontent.com/4284691/41388381-90cc30f6-6f40-11e8-8ded-1785105da548.png">

# Twitter - SF

> 1,412 followers

> It seems there are substantially less followers for both NYC & LA Twitter accounts so it might be more ideal to consolidate these into one Techqueria Twitter account? Just a suggestion.

<img width="1919" alt="screenshot 2018-06-13 19 30 37" src="https://user-images.githubusercontent.com/4284691/41388382-90eec382-6f40-11e8-8d6b-beda5dc65cef.png">

# Twitter - LA

> 182 followers

<img width="1920" alt="screenshot 2018-06-13 19 30 48" src="https://user-images.githubusercontent.com/4284691/41388383-912831b2-6f40-11e8-91b9-baae20bab0c0.png">

# Twitter - NYC

> 134 followers

<img width="1920" alt="screenshot 2018-06-13 19 30 59" src="https://user-images.githubusercontent.com/4284691/41388384-9145a1d4-6f40-11e8-8ec0-018ccabfc68e.png">

# YouTube

> 769 views, 24 subscribers

<img width="1920" alt="screenshot 2018-06-13 19 31 23" src="https://user-images.githubusercontent.com/4284691/41388385-9165858a-6f40-11e8-86ba-e2ccb9d92e0d.png">

# GitHub

<img width="1035" alt="screenshot 2018-06-13 19 32 09" src="https://user-images.githubusercontent.com/4284691/41388389-9248c4bc-6f40-11e8-8483-0a8454fe1e6b.png">

# Current Website

<img width="806" alt="screenshot 2018-06-13 19 31 56" src="https://user-images.githubusercontent.com/4284691/41388386-91aa292e-6f40-11e8-9a71-33c8abd97959.png">
<img width="402" alt="screenshot 2018-06-13 19 32 01" src="https://user-images.githubusercontent.com/4284691/41388387-91ff6286-6f40-11e8-90af-167b3616460a.png">

**Comment by dvidsilva** [comment]
![logo-rectangular](https://user-images.githubusercontent.com/1588753/43170328-674883ae-8f59-11e8-9fa2-86f91f86dace.png)
![logo-squared](https://user-images.githubusercontent.com/1588753/43170415-e37714b8-8f59-11e8-92ed-6512cf4d8132.png)

Added new logo versions that are more consistent, creating a new issue to make a media kit page. We can use this logos in the site too or other social medias.

**Comment by dvidsilva** [comment]
![logo-rectangular-no-url](https://user-images.githubusercontent.com/1588753/43170696-32607f3c-8f5b-11e8-810d-84933801eb62.png)
![logo-squared-no-url](https://user-images.githubusercontent.com/1588753/43170697-329b3bf4-8f5b-11e8-8a92-08cae6126a7e.png)

**Comment by fvcproductions** [comment]
Just to follow up on this, were all the logos updated across the social media profiles?

**Comment by fvcproductions** [comment]
I think this is all good, right? :smile:

**Comment by fvcproductions** [comment]
@dvidsilva feel free to close out this issue once we verify the logos are consistent across all online techqueria communities

**Comment by dvidsilva** [comment]
Going to close this for now so is less confusing, we can fix the remaining logo locations over time.
