### ISSUE TITLE
New Feature Request: Add team members to summit page

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#705]
## Request

Let's add...

- all the new team members to summit page (Name, Image, Role, LinkedIn)

People to add

- Mary
- Maria
- Felipe

## URL(s)

https://techqueria.org/summit

## Why did you make this request?

There are more folks involved now

## Any additional context?

N/A

cc @fvntr

**Comment by yarden2k3** [comment]
Hi! I can see that information already added, is it true?

**Comment by fvcproductions** [comment]
Yes, this was done!
