### ISSUE TITLE
New Feature Request: Add new press articles to Techqueria News

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#709]
## Request

Let's add...

Image, title, and link for all articles below

https://medium.com/@lolitataub/where-latinx-founders-can-find-funding-resources-and-more-9771530626d1

https://oscarbarillas.com/list-of-latinx-in-tech-communities

https://technical.ly/philly/2020/06/15/shannon-morales-founder-echo-me-forward-philly-hires-black-techqueria/

https://www.yesmagazine.org/issue/coronavirus-community-power/2020/05/09/technology-diversity/

https://abc7news.com/community-events/abc7-celebrates-latino-heritage-month-2019/5538011/

## URL(s)

https://techqueria.org/news

## Why did you make this request?

To showcase all the external places we are mentioned

## Any additional context?

N/A

**Comment by celioreyes** [comment]
Hello 👋 

Is the plan for these `news` post to only be a link to the external posts? Or would there need to be a recap of the external post and a link?

**Comment by fvcproductions** [comment]
A small recap would suffice as well as linking to external site
