### ISSUE TITLE
New Feature Request: Embed Triplebyte in footer for 1 month

### ISSUE THREAD

**Issue by FrancesCoronel** [techqueria/website#710]
## Request

Let's add...

Experiment: Add Triplebyte screenshot to content footer for 1 month - September 15 to October 15

## URL(s)

All pages - right under "Donate" section on pages

<img width="1256" alt="Screen Shot 2020-08-17 at 7 55 44 PM" src="https://user-images.githubusercontent.com/4284691/90455328-cd8c7400-e0c3-11ea-8656-4ce53faaaab8.png">

## Why did you make this request?

For promotion of Triplebyte - for every person that signs up, they will donate $10 to Techqueria

## Any additional context?

N/A

**Comment by fvcproductions** [comment]
Screenshot is here: https://techqueria.org/supporters/triplebyte/

**Comment by fvcproductions** [comment]
Link is https://triplebyte.com/a/Wergxwo/d

**Comment by DianiSN** [comment]
@fvcproductions - Do you want the screenshot 
![image](https://user-images.githubusercontent.com/8972507/94947673-0a61ce00-04ac-11eb-9ddc-afedaad02935.png) to be just like it is in that page? That they click and go to https://triplebyte.com/a/Wergxwo/d?

**Comment by fvcproductions** [comment]
yep that's right

**Comment by DianiSN** [comment]
Sounds good :) will do.
