### ISSUE TITLE
New Feature Request: CSS For Help Center

### ISSUE THREAD

**Issue by FrancesCoronel** [techqueria/website#714]
## Request

We need a CSS file for our new Help Center powered by Help Scout

## URL(s)

https://help.techqueria.org

## Why did you make this request?

The default theme is pretty ugly, we need to use our branding

## Any additional context?

This needs to be...

https://techqueria.org/brand

https://docs.helpscout.com/ is good example

https://docs.helpscout.com/article/562-docs-branding-examples

![screencapture-help-techqueria-org-2020-08-17-20_49_44](https://user-images.githubusercontent.com/4284691/90458021-32979800-e0cb-11ea-9da6-3ac5d059ff12.png)
![screencapture-secure-helpscout-net-settings-docs-site-5ebac665042863474d1a91ba-2020-08-17-20_49_28](https://user-images.githubusercontent.com/4284691/90458022-33302e80-e0cb-11ea-8095-3efd9ab07de1.png)

**Comment by PeppermintNDaisies** [comment]
Hello! I would love to work on this issue!

**Comment by fvcproductions** [comment]
@PeppermintNDaisies Just assigned you!

**Comment by PeppermintNDaisies** [comment]
How exciting, thanks!

**Comment by PeppermintNDaisies** [comment]
Hello @fvcproductions ! I forked the repository and didn't find the help center page there, I later came back here and found the page is hosted in Help Scout. I went there for some guidance and found [this](https://docs.helpscout.com/article/835-css-styles-to-snag), but I'm not sure how to proceed, is the code somewhere I can see it or use it to test the CSS?

**Comment by FrancesCoronel** [comment]
Heyo, so the help center code is hosted on Help Scout but what you can do is grab the HTML and apply the CSS locally using the guide.

**Comment by PeppermintNDaisies** [comment]
Perfect! That sounds good, where can I get that HTML from? Where is that code located?

**Comment by FrancesCoronel** [comment]
https://help.techqueria.org/ has the current HTML

**Comment by FrancesCoronel** [comment]
[help-site.zip](https://github.com/techqueria/website/files/5380069/help-site.zip)

This is what I was working on

**Comment by PeppermintNDaisies** [comment]
Perfect, thanks!!
