### ISSUE TITLE
New Content Update Request: New sponsor

### ISSUE THREAD

**Issue by marieram** [techqueria/website#719]
## Link where content currently exists
https://techqueria.org/supporters/

## Updates you'd like to make
The first paragraph needs to be updated to include Hired as an 📣Affiliate Partners📣

## Any additional context?
This was requested because a new partnership agreement was signed.

**Image to use**
![Hired-Avatar-YT-800x800](https://user-images.githubusercontent.com/34839209/91785576-8cfc2280-ebba-11ea-989e-762fffb320c6.png)

**Caption to use on the landing page**

We have partnered with Hired, the largest software engineering job platform, to help engineers find a job they’ll love. Hired uses intelligent job matching algorithms to reduce hiring bias by focusing on the candidate’s skills and preferences. Upload your resume here to signup and companies will apply to interview you, with salary and compensation shown upfront. Make sure to mark “open to remote” to increase your chances of landing interviews from their many companies, including many Fortune 50 companies. Hired’s focus is on finding engineers jobs, but they often have other tech roles including Product Manager, UI/UX Design, and others. Sign up in minutes here: https://hired.com/techqueria

**Comment by yarden2k3** [comment]
Hi, I would like to take that task and help:) I'm already creating a PR it should be done in a few minutes.

**Comment by marieram** [comment]
@fvntr can we push this to the website?
