### ISSUE TITLE
Company Logo Width from some cards are cut off

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#73]
See attached
<img width="766" alt="screen shot 2018-10-06 at 16 54 34" src="https://user-images.githubusercontent.com/1316570/46569529-197b1780-c989-11e8-8b69-4dc16db8127f.png">

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by joaoluizn** [comment]
I'm going to work on this :)

**Comment by fvntr** [comment]
Closing this for now, we still have the informedk12 logo pending will create a new issue for that
