### ISSUE TITLE
New Content Update Request: Remove any images with namecards visible

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#735]
## Link where content currently exists

lhm summit page and other event pages

## Updates you'd like to make

replace with images without names or alter image to remove names

## Any additional context?

Maritza brought this to my attention as a potential privacy concern.

**Comment by DianiSN** [comment]
@fvntr Can we get a little bit more of a description of the issue? A screenshot would help tons. What is the issue? What is the desired state? Where are the images in the LHM Summit page? Is it the speaker images that you are referring to?

**Comment by fvntr** [comment]
There are images on the site like techqueria.org/summit where the names of participants are visible if you zoom in.

**Comment by FrancesCoronel** [comment]
@fvntr i would upload replacement images

**Comment by FrancesCoronel** [comment]
No longer relevant
