### ISSUE TITLE
reopen store

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#74]
we should reopen/create an online store for merch 

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvntr** [comment]
we can do use the prev existing store or look into another option

**Comment by fvntr** [comment]
@dvidsilva was it at shopify?

**Comment by dvidsilva** [comment]
We've never had a store. I ran a teespring campaing once that virtually no one bought into. Feel free to open whatever you'd like

**Comment by fvcproductions** [comment]
For reference: https://teespring.com/shop/techqueria

**Comment by fvntr** [comment]
working on it. will be up before black friday :D

**Comment by fvcproductions** [comment]
@fvntr Any update on this? We could just add a new link to the store in navbar

**Comment by fvntr** [comment]
no store yet lets close for now.
