### ISSUE TITLE
New Content Update Request: New sponsor

### ISSUE THREAD

**Issue by marieram** [techqueria/website#743]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

The first paragraph needs to be updated to be updated under 🧭Silver Sponsors🧭

## Any additional context?

This was requested because a new partnership agreement was signed.

![northeastern-university](https://user-images.githubusercontent.com/34839209/94323349-47790e00-ff4a-11ea-9ef0-677dbcdb20e9.png)

**Comment by yarden2k3** [comment]
Hi, I would love to work on that issue.
Can you please send some additional information about that university (only one paragraph so I could elaborate on the new page)?

**Comment by DianiSN** [comment]
Was this already taken care of?

**Comment by fvcproductions** [comment]
Hi this wasn't done yet but I would just grab some info from the Wiki page

**Comment by DianiSN** [comment]
Sounds good. I will do that.

**Comment by AdhilUsman** [comment]
Can i work on that?

**Comment by DianiSN** [comment]
> Can i work on that?

I have a open PR for this #770.
