### ISSUE TITLE
Create page highlighting the organization and member's open source projects

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#75]
We should include a section that highlights techqueria's open source projects and open source projects that are run by members as well as a form requesting that their projects be added to this section
---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
@fvntr Let's make sure to add labels to any new issues created so folks have an idea of what it entails. Thanks! 👍

**Comment by fvntr** [comment]
cool. can we get a list going?

**Comment by kylemh** [comment]
👋 I maintain https://github.com/OperationCode/front-end and obviously there's a huge presence of latinx within the United States military ❤️

**Comment by fvcproductions** [comment]
This can be put under "resources" section for now within an "Open Source" folder.

Ergo, I think we should open a PR with @kylemh Operation Code repo cause it's a great org. As we get more orgs up, we can add them on too.
