### ISSUE TITLE
New Content Update Request: LHM page

### ISSUE THREAD

**Issue by marieram** [techqueria/website#774]
## Link where content currently exists

https://techqueria.org/summit/#speakers

## Updates you'd like to make

Remove the speaker called Austin Hernandez and add Stephanie Rivera, Full Stack Bureaucrat, 18F.

## Any additional context?

This was requested because the panelist were changed. 
![image (21)](https://user-images.githubusercontent.com/34839209/95110846-7da95100-06f3-11eb-87a0-b03308e7b2ac.png)

**Comment by gdomingu** [comment]
i think someone already completed this. 
<img width="488" alt="Screen Shot 2020-10-08 at 11 51 17 AM" src="https://user-images.githubusercontent.com/4443635/95501062-99fbf680-095c-11eb-990f-abdbc335541d.png">

**Comment by FrancesCoronel** [comment]
Yep, looks like it - thank you for flagging!
