### ISSUE TITLE
Include 10/17 Mixpanel event to Event 

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#78]
Add mixpanel event
---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by dvidsilva** [comment]
merged the PR but still missing to be added as sponsors so we'll keep this open. Going to bed now, good work

**Comment by fvntr** [comment]
ill make a separate issue for sponsor, its a good ticket for a new contributor to pickup
