### ISSUE TITLE
New Content Update Request: New Partner

### ISSUE THREAD

**Issue by marieram** [techqueria/website#787]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Please add under community partners

## Any additional context?

This was requested because we have a new partner. 

![LUCS-logo-vert-nobg](https://user-images.githubusercontent.com/34839209/96775733-cd974180-139c-11eb-9a26-61cb8feacbeb.png)

**Comment by DianiSN** [comment]
I can take care of this
