### ISSUE TITLE
New Content Update Request: New Partner

### ISSUE THREAD

**Issue by marieram** [techqueria/website#788]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Update should happen under bronze supporters 

## Any additional context?

This was requested because its a new partner.

![Sisense-logo_alternate_black_small](https://user-images.githubusercontent.com/34839209/97044682-49be9000-1529-11eb-84a4-31b41aa848b3.png)

**Comment by DianiSN** [comment]
I can take care of this
