### ISSUE TITLE
New Content Update Request: New Partner Meet Cafecito

### ISSUE THREAD

**Issue by marieram** [techqueria/website#804]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Add the sponsor logo under the"Community Partners" section

## Any additional context?

This was requested because we have a new partner.
![Group 23](https://user-images.githubusercontent.com/34839209/98571596-ef843580-2271-11eb-996f-ab6ebe0046ee.png)

**Comment by DianiSN** [comment]
@marieram - What is the name of the new partner?

**Comment by FrancesCoronel** [comment]
Meet Cafecito

**Comment by DianiSN** [comment]
Great! I am on it.
