### ISSUE TITLE
New Content Update Request: Supporter

### ISSUE THREAD

**Issue by annelisehp** [techqueria/website#811]
## Link where content currently exists

https://https://techqueria.org/supporters/

## Updates you'd like to make

Add 1 additional donor to Supporters page under "Patreon supporters who pledge $25 or more each month" section:

<img width="750" alt="Screen Shot 2020-11-16 at 1 41 05 PM" src="https://user-images.githubusercontent.com/74083018/99311407-6b055a00-2811-11eb-9d88-d42165f53837.png">
Zak Quintanilla 
Managed Office Business Analyst at Novatech
[LinkedIn Profile ](https://www.linkedin.com/in/zakquintanilla/)

## Any additional context?

This is being requested because this is a new Patreon donor and as a part of our commitment, we feature them on our Supporters page.

**Comment by DianiSN** [comment]
On it 👍
