### ISSUE TITLE
New Content Update: Article

### ISSUE THREAD

**Issue by FrancesCoronel** [techqueria/website#818]
Add this article under news as we are mentioned

We got mentioned in another article!

> For any interview always dress up, bring a water bottle, extra resumes and arrive early.  In hindsight give yourself grace, carve out a few hours a day to apply to jobs, and try to network as much as possible through LinkedIn/Slack groups.  Being Latino in the tech industry, I volunteer for a group named Techqueria that posts jobs, resources, and mentorship events via Slack.  I highly recommend any Latinos interested in tech to join. It's free and we would love to have you

https://lbpost-com.cdn.ampproject.org/c/s/lbpost.com/news/millennials-great-recession-how-to-get-a-job-advice/amp/

**Comment by DianiSN** [comment]
Sounds good. I will add it.
