### ISSUE TITLE
New Content Update Request: New Partner Adyen

### ISSUE THREAD

**Issue by marieram** [techqueria/website#822]
![Adyen logo - Green RGB](https://user-images.githubusercontent.com/34839209/102822182-cb019a00-4395-11eb-8fdf-cc6b1667b24b.png)

## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Please add the image under Silver Sponsors. 

## Any additional context?

This was requested because they're a new partner.

**Comment by DianiSN** [comment]
I will update the sponsors

**Comment by michellbrito** [comment]
opened a new pr for this - https://github.com/techqueria/website/pull/834
