### ISSUE TITLE
New Content Update Request: New Partner Latino Community Fund WA

### ISSUE THREAD

**Issue by marieram** [techqueria/website#823]
![lcf logo](https://user-images.githubusercontent.com/34839209/102822621-af4ac380-4396-11eb-9b94-136401a17750.png)
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Please add the partner under Community Partner

## Any additional context?

This was requested because they're a new partner.

**Comment by DianiSN** [comment]
I will update the partners
