### ISSUE TITLE
New Content Update Request: Article

### ISSUE THREAD

**Issue by marieram** [techqueria/website#824]
## Link where content currently exists

https://techqueria.org/news/

## Updates you'd like to make

Add the following ... https://www.lyft.com/diversity

Lyft's 2020 Diversity Report highlights many partnerships across the industry to include Techqueria. 
Techqueria and Lyft partnered hosted [Uncharted Territories: On Being First in Tech](https://events.techqueria.org/events/details/techqueria-virtual-events-presents-uncharted-territories-on-being-the-first-in-tech/) which resulted in over 800 RSVP's and remains one of Techqueria's most successful event to date.

## Any additional context?

This was requested because...

**Comment by DianiSN** [comment]
I will add this article

**Comment by DianiSN** [comment]
@marieram - Do you want me to add the text you included as the summary? I would put today's date as the date for the article. Is that alright?
