### ISSUE TITLE
New Content Update Request: New Partner Guru

### ISSUE THREAD

**Issue by marieram** [techqueria/website#825]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Please add the image under Silver Sponsors.

## Any additional context?

This was requested because they're a new partner.

![05_GuruG_WTagline_Green (1) (2)](https://user-images.githubusercontent.com/34839209/103025892-f14b4500-450f-11eb-922f-e04bee75f822.png)

**Comment by DianiSN** [comment]
I will make the update.
