### ISSUE TITLE
New Content Update Request: Update Miami Slack Channel Name

### ISSUE THREAD

**Issue by annelisehp** [techqueria/website#829]
## Link where content currently exists

https://techqueria.org/chapters/miami/ 
https://techqueria.org/chapters/

## Updates you'd like to make

Update Slack channel name to #locals-florida (currently #locals-miami_

## Any additional context?

This was requested because I noticed Miami is an incubating chapter and Orlando is inactive. The linked Slack channel goes to a Florida channel, not Miami. May be a good opportunity to reactive a broader FL chapter.

**Comment by FrancesCoronel** [comment]
Done
