### ISSUE TITLE
New Feature Request: Showcase Guidestar Platinum Seal on site

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#849]
## Request
We have a platinum seal on guidestar and can showcase it on the site: 
https://learn.guidestar.org/news/news-releases/2011/guidestar-exchange-seal-holders-can-now-display-seal-on-own-sites

## URL(s)

should be on the frontpage https://techqueria.org/

## Why did you make this request?

Will help with donors

**Comment by FrancesCoronel** [comment]
Done
