### ISSUE TITLE
New Feature Request: Form for member discounts

### ISSUE THREAD

**Issue by FrancesCoronel** [techqueria/website#863]
## Request

Would like to add a form to collect ticket discounts for members from events/conferences/programs/business/etc.

## URL(s)

https://techqueria.org/submit-discount

alias: /submit-member-discount

## Why did you make this request?

We have a lot of different folks reaching out to us to advertise something and we are open to doing it if they share a good discount for our members - this will streamline that process by piping all form submissions to partnerships@techqueria.org and make it easier to collect info up front

## Any additional context?

Some potential fields

Name of Person
Name of event/program/etc
Why Techqueria
Discount info for members (how many discounts, how much is discount, anything else you can offer)

**Comment by DianiSN** [comment]
@FrancesCoronel would this be under the Partner menu item?

**Comment by FrancesCoronel** [comment]
@DianiSN Great question, this could actually go under the Donate page so it would be above Donate Space on https://techqueria.org/donate and would be a form to donate conference tickets or discounts to members in exchange for marketing. I'm also open to having it be added to existing partner form where it can be selected as an option

**Comment by michellbrito** [comment]
Should I assign this to you? @DianiSN

**Comment by DianiSN** [comment]
> Should I assign this to you? @DianiSN

Yes please! I will submit my PR today or send a screenshot of what it looks like just to make sure I am going in the right direction.

**Comment by DianiSN** [comment]
@FrancesCoronel this is what I have so far for the form. 
<img width="402" alt="Screen Shot 2021-03-17 at 6 55 17 PM" src="https://user-images.githubusercontent.com/8972507/111550086-ca3d9180-8753-11eb-834c-e450fcc1089d.png">

I have placed it under "Donate Space". I am not familiar with how to make sure that the form gets sent to partnerships@techqueria.org. Can you guide on that? Thank you!
