### ISSUE TITLE
New Article: Lyft D&I Report 2020

### ISSUE THREAD

**Issue by FrancesCoronel** [techqueria/website#866]
## Request

Add Lyft D&I report mention under news

## URL(s)

https://www.lyft.com/diversity

https://assets.ctfassets.net/q8mvene1wzq4/2uZXTbWM98UL3KXJDfXsT5/54190edef9d185bb7fffa14eeb71a633/Lyft_Inclusion_Diversity_and_Racial_Equity_2020_Report.pdf

## Why did you make this request?

> To showcase success of Lyft partnership

page 11: Notwithstanding these significant disruptions to the business landscape, we were
intent on minimizing the impact on our long-term workforce representation
strategy. Even in the midst of the pandemic and the resulting economic
uncertainty, we launched new initiatives like our revised “Rooney Rule 2.0,”
hosted opt-in internal focus groups with team members who self-identified as
two or more racial identities to inform how we capture and report intersectional
workforce data, and formed new partnerships with organizations like Techqueria
and Blavity/AfroTech in order to keep the talent pipeline open and flowing.

page 15: Such efforts to build a diverse talent pipeline require collaboration and
cooperation. This year, we partnered with organizations like Techqueria,
Latinas in Tech, Nextplay, SHPE, Anita B, Blavity / AfroTech, and Pursuit,
working alongside them to offer Black and Latinx professionals networking and
mentorship opportunities. These partnerships have led not just to a number of
successful events, but to more applications from Black and Latinx candidates
and better interview readiness scores.

**Comment by michellbrito** [comment]
@FrancesCoronel I believe this was already added in the news section. 

https://techqueria.org/news/2021/01/14/inclusion-diversity-and-racial-equity/

**Comment by FrancesCoronel** [comment]
Oh good point, I can close this then. Thank you!
