### ISSUE TITLE
New Feature Request: Add Shopify event to past events

### ISSUE THREAD

**Issue by FrancesCoronel** [techqueria/website#869]
## Request

Let's add Shopify event to past events

https://event.webinarjam.com/register/25/py524cxx

## URL(s)

https://techqueria.org/past-events

## Why did you make this request?

All past events should be reflected

**Comment by michellbrito** [comment]
@FrancesCoronel when did this event happen? Can't seem to find that info on https://event.webinarjam.com/register/25/py524cxx

**Comment by FrancesCoronel** [comment]
Friday, April 24, 2020
Time: 3 PM - 4 PM PT
