### ISSUE TITLE
Add donation link that links to patreon account

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#89]
Link to patreon account 
Where do you think the best place to put this on the site is? 

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
We can put in on the bottom of every single page or just on the Contact Page - depends on how much visibility we want to give it.

Can you link the Patreon account here so someone can take a look at it? 

As for the design, we would just use or something similar - I already have the asset.

![Patreon](https://d33wubrfki0l68.cloudfront.net/32965feaabf61f1968d917d67cc32d3e041d7351/c2f38/assets/img/donate/patreon.svg)

**Comment by fvntr** [comment]
awesome. yeah I just made an account at patreon.com/techqueria

**Comment by fvntr** [comment]
https://github.com/techqueria/website/pull/94
