### ISSUE TITLE
New Content Update Request: New Partner update Sisense, Pocket Gems, Guru and Adyen 

### ISSUE THREAD

**Issue by marieram** [techqueria/website#916]
## Link where content currently exists

https://techqueria.org/supporters/

Add the following logos under Sponsors:

![PG_FlatLogo_BLKBLU](https://user-images.githubusercontent.com/34839209/111094305-a8000580-8500-11eb-941c-f66e156d88ac.png)
![Sisense-Logo-Photo-2](https://user-images.githubusercontent.com/34839209/111094433-e5649300-8500-11eb-889c-eb91f8a0554e.png)

## Any additional context?

- For some reason #822 and #825 aren't currently reflected on the website and they should be under Sponsors. 
- Please add Pocketgems and Sisense under Sponsors as well.

**Comment by DianiSN** [comment]
I can update this. I have the changes and logos for the partner's that are not reflected on the website.

**Comment by DianiSN** [comment]
LinkUpconferenceShow from issue #787 is also missin.

**Comment by DianiSN** [comment]
It seems that the partners were under categories that no longer exist on the page. I will add them all under the category sponsor.

**Comment by DianiSN** [comment]
This is what the sponsors section would look like 
<img width="739" alt="Screen Shot 2021-03-15 at 9 52 42 PM" src="https://user-images.githubusercontent.com/8972507/111245158-912de180-85da-11eb-9c9a-9b6f61aa7ddd.png">
