### ISSUE TITLE
New Content Update Request: Partnership Inquiry Form

### ISSUE THREAD

**Issue by marieram** [techqueria/website#917]
## Link where content currently exists

https://techqueria.org/partner/#submit-a-partnership-inquiry

## Updates you'd like to make

- Please remove _What is your LinkedIn profile URL?*_
- On _How is your organization interested in partnering with Techqueria?*_ remove the _events_ option and add _monthly career fair_ option
- On _What kind of partnership is your organization interested in?*_ remove the _affiliate partner_ option

Additions:
- Where _What is your LinkedIn profile URL?*_ currently lives, please remove it and replace it with _What is your organization's website URL*_?

Under the website URL question, please add the following questions and sequence them similar to *Your first name* and *Your last name* fields:
- How many women are in the organization?
- How many people of color are in the organization?
- How many Latinx people are in the organization?
- How many LGBTQIA+ folks are in the organization?
- How many folks with disabilities are in the organization?
- How is your workplace inclusive? _Open multiline Text box_
- Does your organization hire DACA recipients? _Yes or No drop down._

Under the questions above, please add the following question:
- Does your organization have a DEI, Impact or Sustainability report we can reference? If so, please provide the URL below.

## Any additional context?

This was requested because of changes to how partners are vetted and partnership offerings available in 2021.

**Comment by DeolaJ** [comment]
Hello. Please is help still needed on this task?
