### ISSUE TITLE
New Content Update Request: New Partner Realtor.com

### ISSUE THREAD

**Issue by marieram** [techqueria/website#943]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Add the image to 💎Sponsors💎

## Any additional context?

This was requested because realtor.com
![realtor_dot_com_logo_detail](https://user-images.githubusercontent.com/34839209/113216817-23202600-923a-11eb-8f4e-f7180d3beae8.png)
 is a new partner.

**Comment by Karthik-59** [comment]
Hi there, Can I change this ? I just need to add realtor.com in sponsors right ?
