### ISSUE TITLE
New Content Update Request: New Partner Square

### ISSUE THREAD

**Issue by marieram** [techqueria/website#970]
## Link where content currently exists

https://techqueria.org/supporters/

## Updates you'd like to make

Please add under:
💎Sponsors💎

## Any additional context?

This was requested because they're a new partner.

![Square_Logotype_black](https://user-images.githubusercontent.com/34839209/115051797-7204c700-9e9a-11eb-82d3-4fb479163c94.png)

**Comment by DianiSN** [comment]
I can work on this one :)
