### ISSUE TITLE
Replace linkedin links with a short internally hosted bio of each organizer

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#98]
We should have a section that has a short bio of all organizers with the links to their social media if they want instead of just a link to to their linkedin.

That way people on the site can find out more about each of us without navigating outside of the site. 
Its also a good opportunity to share our connection to this space and what each of us are passionate about. 

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvntr** [comment]
we need to collect these

**Comment by fvcproductions** [comment]
This is a great idea but yeah first we need to collect all their profile picture images.

**Comment by fvcproductions** [comment]
Would look similar to https://techqueria.org/testimonials/

**Comment by fvntr** [comment]
we can use linkedin photos for now

**Comment by Bedrock02** [comment]
Also do we want to keep this new content under the about page? Or should we have a submenu with About and another one with Team. Keeping the more about us section on the bottom of both pages.

**Comment by fvntr** [comment]
there is no branch as of now. I think the about page is getting too busy so your ideea of having a submenu is good. Thoughts @fvcproductions @dvidsilva

**Comment by Bedrock02** [comment]
Maybe something like this???
Just an example.
https://github.com/techqueria/website/pull/162

**Comment by Bedrock02** [comment]
It creates a page "Organizers" with sections for each region (NY, LA, Austin, Bay Area ). Upon click we would have a page with an individual section for each organizer based in that chapter.

This approach takes the same layout as testimonials.

**Comment by fvntr** [comment]
nobody has posted them here, but there scattered on the trello board
yeah in my opinion it makes sense I just dont think it should be a standalone page for each necessarily

**Comment by fvntr** [comment]
I think that instead of the organizer cards hyperlinking to linkedin it should be we can have a list of social media links underneath depending which ones folks wanna share

**Comment by andreancardona** [comment]
@fvntr 

[https://docs.google.com/document/d/16jpFuuOEuwAHJJpSPMVxAGwORd3P6VCebucGUfJ6PJE/edit](url)

- so sorry for the delay!!
- The link above has my bio and photo

**Comment by fvcproductions** [comment]
@fvntr I think we should create separate issues to update the info for each organizer as we get their info and close this one for now. Will create a new issue for @andreancardona bio info.
